### ISSUE TITLE
Расход оперативки при заливке файлов

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#108]
![default](https://user-images.githubusercontent.com/8224786/32697113-c48c431c-c799-11e7-8ea6-c8a08ceed293.png)

**Comment by pasha-zzz** [comment]
При этом скорость заливки была 25+ МБ/с вместо положенных 7-8

**Comment by yar229** [comment]
А какой клиент? Не диском в винде, случаем, подключено?

**Comment by pasha-zzz** [comment]
Неа. Клиенты WinSCP и Far NetBox

**Comment by yar229** [comment]
Вот такого не было в логе - Client does not send file size, caching in memory
Повторно пробовали?  Получилось, нет?

**Comment by pasha-zzz** [comment]
Так вроде клиентов не менял, WinSCP этой версии работал на ура. Сейчас догрузится задание - попробую запустить в консоли (у меня забускается службой, консоль не видно).
Единственное большое изменение - перешел с .NET на .NET Core

**Comment by yar229** [comment]
Ну и вдогонку, конечно - а на net45 версии закачивается?
А на предыдущей?

**Comment by pasha-zzz** [comment]
Все это и буду пробовать, но чуть-чуть попозже

**Comment by pasha-zzz** [comment]
.NET 4.5 отработал на ура. Только 1 исключение в начале закачки - но это, наверное, так и задумывалось (если файл не существует в облаке):

[3]: Cannot get /<закачиваемое_имя_файла> with exception System.Net.WebException: Удаленный сервер возвратил ошибку: (404) Не найден.

**Comment by pasha-zzz** [comment]
На .NET Core - съедание памяти. Что на текущей, что на первой реально работающей 1.8.0.9 (промежуточные проверять надо?).
Сообщения в логе одинаковые, ничего про память и кэш. Да, на 1.8.0.9 нет вышеуказанного исключения (404).

**Comment by yar229** [comment]
1 исключение в начале - да, нормально, просто раньше его в лог не писал.

Спасибо, буду разбираться с .NET Core

**Comment by yar229** [comment]
Под .Net Framework поведение привычное - клиент втюхивает данные, запрос по мере их прибытия отправляет их дальше, всё ок.
Под .Net Core - сначала всасывает все данные (здесь клиент показывает якобы запредельные скорости закачки), прямо в память в MemoryStream и только потом начинает отправлять дальше. Пока идёт этот процесс, клиент успевает отвалиться по таймауту.

**Comment by yar229** [comment]
Впрочем, говорят, он устарел, надо пользовать HttpClient

https://github.com/dotnet/corefx/issues/7862#issuecomment-211986998
We recommend you move to the newer System.Net.Http API surface which includes HttpClient. This contract/library is part of NETStandard.Library.
In general, for better app performance and features, we recommend developers move away from HttpWebRequest and adopt HttpClient API surface.

Будем пробовать однажды.

**Comment by yar229** [comment]
Беда прямо какая-то, HttpRequest кривой в netCore и его не будут допиливать, HttpClient - наоборот, на десктопе недопилен. 
Можно, конечно, убиться  и написать как надо, но пока тямы не хватает.

Решено в виде разных UploadStream для core и десктопа, выложу в ближайшей версии, когда шифрование допилю.

**Comment by yar229** [comment]
done [1.9.0.1_beta](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.9.0.1_beta)
