### ISSUE TITLE
[REQ] Расшаривание папок/файлов

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#109]
Возможно, через команду переименования, если префикс >>public или что-то типа такого. Вот только куда результат (публичную ссылку) сохранять...

**Comment by pasha-zzz** [comment]
или может, для единообразия, >>link share или >>link public

**Comment by yar229** [comment]
Да, не совсем понятно, как реализовать.
Видимо, да, команда вроде `link share` и ссылка, скажем, в файл `filename.shared.wdmrc`

**Comment by pasha-zzz** [comment]
Но, наверное, в JSON его делать не стоит, я думаю... может что-то типа лога, чтобы дата/время тоже были.

**Comment by yar229** [comment]
Примитивно сделал, выложу в следующем релизе

**Comment by yar229** [comment]
- [ ] Убирать публичный доступ при удалении пользователем файла .share.wdmrc

**Comment by yar229** [comment]
done [1.9.0.1_beta](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.9.0.1_beta)
