### ISSUE TITLE
Automatically encrypt subfolders of an encryption-enabled parent folder

### ISSUE THREAD

**Issue by VADemon** [yar229/WebDavMailRuCloud#121]
На данный момент `>>crypt init` только лишь помечает единственную папку для шифрования. Поэтому, если создать новую папку в `crypt init` папке, то она **не** будет помечена для шифрования.

```
|-- <Cloud>
|   |-- encrypted-yar229
|       |-- .crypt.wdmrc
|       |-- EncryptedFile.doc
|       |-- NewFolder
|           |-- UnencryptedNewFile.doc
```

Следует создать / автоматически перенимать опцию шифрования из каталога выше уровнем. Иначе становится практически невозможной загрузка какой-нибудь большой папки с подкаталогами (вручную прописывать каждой папке перед загрузкой флаг шифрования?)

Я вижу несколько вариантов:

1. Рекурсивно смотреть в родительские каталоги насчет .crypt.wdmrc
2. Смотреть только папкой выше: ../crypt.wdmrc и создавать этот файл в новой подпапке
3. Закреплять флаг шифрования в названии пути: /files/pictures__encrypted/subfolders/...

1) Неосуществим на практике из-за возрастающей нагрузки. Загрузка в 10-ю подпапку и понеслось...
2) Можно. Плюс: можно вручную создать папку подкатологом и не шифровать её. Из этого и минус - можно запутаться. Например, создав нешифрованную папку в веб-интерфейсе/клиенте и залить туда личную информацию.
3) Железобетонный вариант. Минимально страдает удобство чтения (кому как). По мне - интуитивен.

**Comment by yar229** [comment]
Да, подумывал об этом.
И более склоняюсь к 1 варианту, благо 
а) вызовы на листинг каталогов кэшируются
б) кажецца, в протоколе DiskO можно одним запросом несколько папок получить

**Comment by yar229** [comment]
done [1.10.0.5](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.0.5)
