### ISSUE TITLE
При внезапном обрыве соединения...

### ISSUE THREAD

**Issue by madhook** [yar229/WebDavMailRuCloud#122]
Если во время закачки файла на сервер произошел внезапный разрыв соединения между wdmrc и сервером mail.ru:
`[16]: Uploading to /folder/file.exe failed with Unable to read data from the transport connection: The connection was closed.`
, то wdmrc никак не "информирует" об этом программу-качалку. Например, окошко загрузки в CarotDAV может висеть бесконечно долго в статусе загрузки. Похожая ситуация с Air Explorer.
Хотелось бы, чтоб у качалки также сразу проихсодил "разрыв" связи, когда это случается между wdmrc и сервером mail.ru.

**Comment by yar229** [comment]
done [1.10.0.5](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.0.5)
