### ISSUE TITLE
Имя папки на кириллице 

### ISSUE THREAD

**Issue by Aleksus78** [yar229/WebDavMailRuCloud#123]
Невозможно войти в папку,  Total Commander, последняя версия вашего плагина,если меняю имя на латиницу то все в порядке.

**Comment by yar229** [comment]
На 1.10.0.5-dotNet45 у меня не воспроизводится.

Попробуйте в TC в свойствах соединения проставить галку
![image](https://user-images.githubusercontent.com/5150160/34650184-a24b9518-f3cd-11e7-9eab-9bc953d619cc.png)

**Comment by Aleksus78** [comment]
Спасибо ,и правда в ней было дело,до этого не было проблем

**Comment by yar229** [comment]
Не за что :)
