### ISSUE TITLE
Отслеживать свободное место в облаке

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#124]
* cached DiskSize
* +/- on file upload/remove

**Comment by Baton34** [comment]
Я так понимаю, что размер облака в случае mail.ru не определяется вообще никак? Монтирую облако с помощью davsf и df выдаёт размер свободного места равным нулю.

**Comment by maksimus256** [comment]
> Я так понимаю, что размер облака в случае mail.ru не определяется вообще никак? Монтирую облако с помощью davsf и df выдаёт размер свободного места равным нулю.

что то поломалось, раньше работало, но больше недели назад само сломалось, т.е. "вчера" ещё было, а "сегодня" нет
Я запускаю под ubuntu 14.04 с mono 5.14.0.177 и монтирую davfs2/

**Comment by pasha-zzz** [comment]
Из-за того, что свободное место 0 байт, не работает, например, RaiDrive. При копировании говорит "Нет свободного места".

**Comment by yar229** [comment]
fixed [1.10.1.15](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.15)

**Comment by pasha-zzz** [comment]
Работает изумительно! Спс!
