### ISSUE TITLE
Missing domain part

### ISSUE THREAD

**Issue by kuimovvg** [yar229/WebDavMailRuCloud#126]
Не работает если почта для домена используется mail.ru, но адреса не из доменов "mail, @inbox, @bk". Например адрес test@pochta.ru. Выдаёт ошибку 
[Threadpool worker]: Missing domain part (mail, @inbox, @bk) in login, file and folder deleting will be denied

**Comment by yar229** [comment]
Это только предупреждение, оно ни на что не влияет.

Когда в браузере в почту входите, вам показывается окно для входа с pochta.ru?

Дело в том, что oauth полностью не реализован, и зайти можно только с почтой от самой mail.ru.

**Comment by kuimovvg** [comment]
> Это только предупреждение, оно ни на что не влияет.

Войти не удаётся
> Когда в браузере в почту входите, вам показывается окно для входа с pochta.ru?

Нет, захожу на сайт mail.ru, просто в поле логина ввожу test@pochta.ru и пароль. 

> Дело в том, что oauth полностью не реализован, и зайти можно только с почтой от самой mail.ru
(вроде как на данный момент это mail.ru/ua, inbox.ru/ua, bk.ru/ua

На самом деле в версии 1.5.62-67 все работало. Сейчас решил обновить и получил такую ошибку

**Comment by yar229** [comment]
Спасибо, буду смотреть

**Comment by yar229** [comment]
а на [1.9.0.1_beta](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.9.0.1_beta) работает?

**Comment by kuimovvg** [comment]
Да, работает

**Comment by yar229** [comment]
пробуйте [1.10.1.3](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.3)
с ключом `--protocol WebV2`

**Comment by yar229** [comment]
И, кстати, DiskO пробовали с тем же логином?

**Comment by kuimovvg** [comment]
> пробуйте 1.10.1.3
с ключом --protocol WebV2

Так все работает

> DiskO пробовали

его нет для Linux, не пробовал

**Comment by yar229** [comment]
[#dev_reviveV2](https://github.com/yar229/WebDavMailRuCloud/tree/dev_reviveV2)
