### ISSUE TITLE
Авторизация без @mail.ru

### ISSUE THREAD

**Issue by NewSky13** [yar229/WebDavMailRuCloud#127]
С какой-то версии исчезла замечательная возможность авторизовываться без @mail.ru, это связано с самим облаком.mail.ru или это новая фича плагина?

**Comment by yar229** [comment]
Это связано с переходом на другой протокол облака, который не имеет такой возможности. Чтобы использовать её, запускайте с ключом `--protocol WebV2`, но я бы не рекомендовал.
