### ISSUE TITLE
link check и мертвые ссылки

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#133]
По крайней мере на папках не работает: по ссылкам, на которые в браузере выдает 404 команда >>link check не реагирует. Ссылки не чистятся и не попадают в хистори.
Также при входе в удаленную уже папку - отображает пустую папку, а не ошибку.

**Comment by pasha-zzz** [comment]
На файлах тоже не работает link check. Файл так и остается в списке, при попытке копирования такого файла - думает и вываливается по таймауту.

**Comment by yar229** [comment]
Принято, спасибо, скорее всего на неделе погляжу

**Comment by yar229** [comment]
Не получилось воспроизвести, на версии 1.10.1.11 у меня под Windows Commander 
F7  `>>link check`
отрабатывает нормально.

Нужен тестовый пример, на котором воспроизводится.

**Comment by pasha-zzz** [comment]
Он оказывается просто вылетает:

[5]: MKCOL:http://127.0.0.1:6443/%3e%3elink%20check/:127.0.0.1:6443 - Finished (2713ms, HTTP 201)

Необработанное исключение: [5]: PROPFIND:http://127.0.0.1:6443/:127.0.0.1:6443 - Processing
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в YaR.MailRuCloud.Api.Base.Repos.WebM1RequestRepo.GetDownloadStreamInternal(File afile, Nullable`1 start, Nullable`1 end)
   в YaR.MailRuCloud.Api.Base.Repos.WebM1RequestRepo.GetDownloadStream(File afile, Nullable`1 start, Nullable`1 end)
   в YaR.MailRuCloud.Api.MailRuCloud.DownloadFileAsString(File file)
   в YaR.MailRuCloud.Api.MailRuCloud.<DownloadFileAsString>d__54.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в YaR.MailRuCloud.Api.Links.LinkManager.<RemoveDeadLinks>d__14.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в YaR.MailRuCloud.Api.MailRuCloud.<RemoveDeadLinks>d__63.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
[5]: Cache hit: /

**Comment by pasha-zzz** [comment]
Клиент любой, пробовал тотал, фар, винсцп

**Comment by yar229** [comment]
Не воспроизводится, закрываю.
Если таки повторится, будем разбираться
