### ISSUE TITLE
ECB encryption mode instead of CBC, why?

### ISSUE THREAD

**Issue by rraallvv** [yar229/WebDavMailRuCloud#134]
Sorry to bother with this kind of question, but I've read in one of the answers in the SO thread related to `SeekableAesStream` that CBC mode is preferred over ECB. Maybe I'm misinterpreting the OP, but I changed the cypher mode to CBC, and it works just fine. So, that's why I'm asking. Again I might be totally wrong in my assumptions, since I'm not into the details of how those modes differ, nor whether just that one-liner change is enough to properly enable CBC mode.

Keep up the good work!

**Comment by yar229** [comment]
Thanks!

Using ECB you could manage a partial decryption. With CBC if you are missing a few blocks in the sequence encryption becomes impossible.
For example, you can play a random part of encrypted movie without downloading and decrypting it from the start.

**Comment by rraallvv** [comment]
Thanks for the clarification, it's very much appreciated.
