### ISSUE TITLE
При запуске службы открывается окно консоли

### ISSUE THREAD

**Issue by ju0k** [yar229/WebDavMailRuCloud#136]
Указанное окно не закрывается само, а если закрыть его самостоятельно то к диску больше нельзя подключиться.
![default](https://user-images.githubusercontent.com/38860804/39433656-130c52a4-4c9f-11e8-93d1-02c818caf0ef.png)
Устанавливал следующим образом:
`wdmrc.exe --install wdmrc --port 801,802 --maxthreads 15`
`net start wdmrc`
Для запуска использую bat файл:
`taskkill /im wdmrc.exe`
`start "WebDAV Cloud Mail.Ru" wdmrc.exe -p 3332`
`ping 127.0.0.1 -n 6 > nul`
`net use V: /DELETE`
`net use V: http://127.0.0.1:3332 пароль /USER:почта`
ОС win 10 pro x64 (1709)

**Comment by ju0k** [comment]
Спасибо огромное, я чайник в этом деле поэтому если не трудно подскажите еще как сделать автоподключение диска при запуске компьютера?
Заранее спасибо

**Comment by yar229** [comment]
Убедиться, что сделано (ну вдруг не заметили)
* [Разрешаем Basic Auth для встроенного в Windows WebDAV](https://gist.github.com/yar229/4b702af114503546be1fe221bb098f27#basicauth)
* [Ограничение максимального размер файла для webdav в 5000000 байт, делаем 4Гб](https://gist.github.com/yar229/4b702af114503546be1fe221bb098f27#windowssizelimit)

Запустить консоль `cmd` (просто запустить, без администратора)
Выполнить 
```
net use V: http://127.0.0.1:801 пароль /USER:почта /PERSISTENT:YES
```
Диск будет подключаться всегда, только после перезагрузки спрашивать пароль.

Если лень вводить пароль, то сделать bat файл
```
net use V: /DELETE
net use V: http://127.0.0.1:801 пароль /USER:почта
```
и положить в автозагрузку.
