### ISSUE TITLE
Не работает запись файла в подкаталог при монтировании webdav-диска через rclone

### ISSUE THREAD

**Issue by lxnglz** [yar229/WebDavMailRuCloud#137]
Не уверен, на стороне какого продукта проблема, но напишу здесь.
Пытаюсь использовать rclone для монтирования диска Mail.ru.
Завожу через rclone config вот такой вот remote:
webdav http://127.0.0.1:801, пароль: ...., логин: .....
Монтирую диск через rclone следующим образом:
rclone.exe mount <remote-name>: M: --cache-dir c:\temp --vfs-cache-mode writes
В системе появляется диск M:, он нормально читается.
Если пытаюсь скопировать на него (с локального диска) файл _в корень_ - файл нормально копируется, все ок.
Но если пытаюсь скопировать не в корень, а _в подкаталог_, то копирование не удается, а rclone в лог кидает кучу ошибок. Все ошибки заканчиваются словами: Update mkParentDir failed: 412 Precondition Failed.
(с другими webdav-серверам rclone работает нормально).

**Comment by yar229** [comment]
Пробуйте (1.10.1.12)[https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.12]

**Comment by lxnglz** [comment]
заработало. правда теперь, похоже, вылезла проблема на стороне rclone - после некоторых операций (типа переименования файла) попытки открытия файла из облака приводят к зависанию. однако при маппинге webdav-диска средствами Windows таких проблем нет. так что, наверное виноват rclone.

**Comment by yar229** [comment]
Эту задачу закрываю тогда.

Если получится стабильно воспроизвести, сделайте, пожалуйста, новую задачу.
