### ISSUE TITLE
Копирование больших файлов через маппинг облака на логический диск встроенными средствами Windows 10

### ISSUE THREAD

**Issue by lxnglz** [yar229/WebDavMailRuCloud#139]
Если использовать встроенное в Windows 10 средство для маппинга webdav-ресурса на логический диск, то встает проблема ограничения максимального размера файла. По умолчанию в Винде это 50 мегабайт (https://support.microsoft.com/nl-nl/help/2668751/you-cannot-download-more-than-50-mb-or-upload-large-files-when-the-upl). С помощью твика ключа в рееестре этот размер можно увеличить до двух гигабайт (там DWORD, но, видимо, винда берет модуль числа со знаком). Поскольку WebDavMailRuCloud режет большие файлы на куски как раз по 2 гигабайта, то файлы заливаются в облако успешно - Винда каждый кусок воспринимает как файл допустимого размера. Однако вот скопировать такой файл обратно с логического webdav-диска на локальный уже не получается: Винда распознает истинный размер файла и отказывается выполнять копирование.
Можно ли как-нибудь обмануть Винду, чтобы такое копирование больших файлов стало возможным?

**Comment by yar229** [comment]
К сожалению, даже если как-то и можно, я такого метода не нашел.

Использовать сторонние методы - `rclone mount`, NetDrive, WebDrive
