### ISSUE TITLE
Нет доступа на запись

### ISSUE THREAD

**Issue by akrush24** [yar229/WebDavMailRuCloud#140]
При создании любого файла в подмонтированной директории облака, ошибка что файл существует.

пример монтирования:
```
# nohup sudo mono wdmrc.exe -p 801 &
# sudo mount --rw -t davfs http://127.0.0.1:801 /mnt/cloud.mail.davfs/
```
запись файла
```
# echo TEST > test.file
# cp test.file /mnt/cloud.mail.davfs/
cp: cannot create regular file '/mnt/cloud.mail.davfs/test.file': File exists

```

**Comment by akrush24** [comment]
```
# mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

```

```
# uname -a
Linux orangepiplus 3.4.113-sun8i #18 SMP PREEMPT Wed Jan 24 22:10:49 CET 2018 armv7l armv7l armv7l GNU/Linux
```

**Comment by yar229** [comment]
В данный момент нет возможности заняться, если не трудно, посмотрите, на предыдущей версии wdmrc воспроизводится?

**Comment by akrush24** [comment]
Проверил на каждой до версии 1.10.1.9, везде воспроизводится, глубже не стал уходить.
Проверял как на ARM так и на x86, с запуском через mono, везде ошибка при записе любого файла что он уже существует.

**Comment by akrush24** [comment]
+ причем это распространяется только на файлы, директории создаются удачно.

```
# mkdir TTTTTTTTTTTTT
# touch RR.txt
touch: cannot touch 'RR.txt': File exists
```

**Comment by yar229** [comment]
Спасибо, принято, на днях починю

**Comment by akrush24** [comment]
Не хочу надоедать, все таки проект не коммерческий :)
Но все же нет ли результатов по проблеме?

**Comment by yar229** [comment]
Подзабыл, да
А попробуйте как-то так
```
sudo mount --rw -t davfs http://127.0.0.1:801 /mnt/cloud.mail.davfs/ -o uid=user -o gid=user
```
, где user - имя или id пользователя, под которым нужен доступ

**Comment by yar229** [comment]
Нну, видимо, как -то решилось
