### ISSUE TITLE
WDMRC and Firewall

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#141]
Win 10 v1803 x64, WDMRC 1.10.1.12 (version of EXE is wrong 1.10.1.11).
With -h option cannot connect to subj. wdmrc.exe and even mrclient.exe added to fw exeptions for all types of networks.
When I disable fw - all works fine.
Other apps opening listen ports pop up window where I can permit access but not WDMRC.

**Comment by yar229** [comment]
как-то [так](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-windows-firewall-for-database-engine-access?view=sql-server-2017), вместо 1433 указать порт, на котором запущен wdmrc

To open a port in the Windows firewall for TCP access
* On the Start menu, click Run, type WF.msc, and then click OK.
* In the Windows Firewall with Advanced Security, in the left pane, right-click Inbound Rules, and then click New Rule in the action pane.
* In the Rule Type dialog box, select Port, and then click Next.
* In the Protocol and Ports dialog box, select TCP. Select Specific local ports, and then type the port number of the instance of the Database Engine, such as 1433 for the default instance. Click Next.
* In the Action dialog box, select Allow the connection, and then click Next.
* In the Profile dialog box, select any profiles that describe the computer connection environment when you want to connect to the Database Engine, and then click Next.
* In the Name dialog box, type a name and description for this rule, and then click Finish.

**Comment by pasha-zzz** [comment]
Hmmmm.... works fine. But "By Program" not.
