### ISSUE TITLE
Повреждение зашифрованного файла при редактировании

### ISSUE THREAD

**Issue by Baton34** [yar229/WebDavMailRuCloud#142]
1. Имеется папка в облаке подключённая через "Подключить сетевой диск" в win10 с шифрованным файлом. Если открыть файл в блокноте из проводника windows, изменить его содержимое (добавил "1" в конце строки) и сохранить, то появляется ещё один экземпляр файлов в облаке, при этом содержимое обоих файлов не соответствует ожидаемому.
было:
![clipboard 1](https://user-images.githubusercontent.com/10797316/44531742-2d7cf980-a6fa-11e8-9d65-df4e1c7913b6.jpg)
стало: 
![clipboard 2](https://user-images.githubusercontent.com/10797316/44531822-58674d80-a6fa-11e8-881b-8ab7563d1527.jpg)
2. Если подключиться к папке через Total Commander с помощью webdav плагина и изменить файл в notepad++, то второго экземпляра файлов не создаётся, но при этом появляется второй зашифрованный файл и содержимое расшифрованного файла снова повреждено:
![clipboard 3](https://user-images.githubusercontent.com/10797316/44532691-661dd280-a6fc-11e8-8654-162dc3345354.jpg)
3. В Ubuntu при монтировании облака через davfs2 и редактировании файла в mcedit ситуация аналогична второму варианту.
4. С незашифрованными файлами таких проблем нет.

WebDAVCloudMailRu-1.10.1.12-dotNet45

**Comment by yar229** [comment]
Исправил, проверяйте [v1.10.1.13](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.13)

**Comment by Baton34** [comment]
Всё равно ломается файл, правда теперь на другом содержимом:
`e:\Programs\Lan\WebDAVCloudMailRu\wdmrc.exe --port 8001`
открываю на редактирование, вставляю в начало строку:
`rem 1`
`e:\Programs\Lan\WebDAVCloudMailRu\wdmrc.exe --port 8001`
сохраняю, файл снова битый:
`rem 1`
`e:\Programs\Lan\WebDAVCloudMailRu\wdmrc.exe --port 8001`
`љЙ+Ўо~*RЃёКInнпmус‡Ц uCLбдbwtтFџ5р†6cЈшzлXАО чр0XeНдёН`

**Comment by Baton34** [comment]
Нет, я не перезапускал wdmrc каждый раз.
Если бы файл открывался с неправильным паролем, как бы я видел его оригинальное содержимое?
Теперь и у меня не воспроизводится.

**Comment by yar229** [comment]
Тогда закрываю таск, если вдруг что- сигнализируйте

**Comment by Baton34** [comment]
Делаю всё также как до этого, только после сохранения изменений нужно файл переименовать.
То, что что-то не  так видно сразу по размеру, он меняется с 57 до 121 байта.
Похоже что-то с кэширования ещё связано, поэтому без переименования файла не видно изменений.
total commander 9.21a x64 + WebDAV plugin v2.9

**Comment by Baton34** [comment]
Ничего не понимаю...
Теперь снова воспроизводится как раньше ...
https://www.dropbox.com/s/iik77w9gc692gdk/2018-08-24_09-41-29.mkv?dl=1

**Comment by yar229** [comment]
Хм-хм...
Вот именно с ситуацией на видео и боролся...
Странно.
Теперь только в понедельник смогу взяться.

**Comment by yar229** [comment]
> Делаю всё также как до этого, только после сохранения изменений нужно файл переименовать.

Да, Total Commander весьма агрессивно кэширует

**Comment by Baton34** [comment]
Возможно я не понял, но в этой строке
`if (remoteFile != null && remoteFile.OriginalSize != file.OriginalSize)`
remoteFile.OriginalSize=64 - это похоже на размер блока зашифрованного файла, а размер расшифрованного файла содержится в remoteFile.Size=57. Когда я редактирую файл размер файла становится равен 64 байтам и это условие не выполняется. Какая-то путаница произошла.
Может стоит вообще всегда удалять оригинальный файл?
`if (remoteFile != null)`

**Comment by yar229** [comment]
Да, вы правы. и размер проверять смысла нет
[1.10.1.14](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.14)
