### ISSUE TITLE
Command line cloud manager

### ISSUE THREAD

**Issue by Hunter23071985** [yar229/WebDavMailRuCloud#144]
[MEGACMD](https://mega.nz/cmd) позволяет из консоли выполнить:
1) Подключение к Облаку (запуск MEGAcmdServer.exe + MEGAcmdShell.exe + login Аккаунт Пароль)
2) Создание папки (mkdir "папка_в_облаке")
3) Синхронизацию папки с шифрованием (sync "диск:/папка_на_ПК" "/папка_в_облаке")
4) Получение публичных ссылок (export -a /"папка_в_облаке/файл")
5) Скачивание публичных ссылок без авторизации (MegaClient.exe get "публичная_ссылка")
Portable получается распаковкой инсталлятора, работает на всех Windows от XP до 10.
Можно ли сделать что-то подобное для Облака Mail.ru?

**Comment by yar229** [comment]
Это WebDAV, а для него люди понаписали много чего, в том числе консольных клиентов, их можно много разных нагуглить.

Под WinXP сам wdmrc работать не будет - для неё нет .NET Framework 4.5.

Например, берём [WinSCP](https://winscp.net/), читаем там документацию по командной строке и
-  Пишем файлик со скриптом `mrc.script`
```
option echo on
option batch abort
option confirm off

echo ----  1. Подключение к Облаку  ----------------------------------------------
open dav://MyAccount@mail.ru#_SEP_:MyPassword_SEP_MySecretPassword@127.0.0.1:3332

echo ----  2. Создание папки  ----------------------------------------------------
mkdir /cmdtest

echo ----  3.1 Создание зашифрованной папки  -------------------------------------
mkdir /cmdtest/crypt
cd /cmdtest/crypt
mkdir ">>crypt init"

echo ----  3.2 Синхронизация локальной папки в зашифрованную папку в облаке  -----
synchronize remote d:\___wcmd\LocalSource /cmdtest/crypt

echo ----  4. a. Покладаем файл для общего доступа  ------------------------------
put d:\___wcmd\LocalSource\1.jpg /cmdtest/

echo ----  4. b. Расшаривание файла  ---------------------------------------------
mkdir ">>share /cmdtest/1.jpg"

echo ----  4. c. Получение файлика, в котором будет публичная ссылка  ------------
get /cmdtest/1.jpg.share.wdmrc

exit
```

- Запускаем `winscp /console /script:mrc.script`

По поводу пункта 5 
- авторизация останется, как-то я не вижу пути, чтобы её убрать и при этом не переколбасить весь проект
- сделать что-то вида `get "https://cloud.mail.ru/public/F5zL/PhVwoXRUz"` скорее всего нетрудно будет, я посмотрю

**Comment by yar229** [comment]
см. https://github.com/yar229/WebDavMailRuCloud/issues/145

**Comment by Hunter23071985** [comment]
**yar229**, скачал [WinSCP 5.13 portable](https://winscp.net/eng/downloads.php).
В строке dav://MyAccount@mail.ru#_SEP_:MyPassword_SEP_MySecretPassword@127.0.0.1:3332
заменил MyAccount на аккаунт, MyPassword на пароль, MySecretPassword на набор цифр.
Результат - "Could not connect to server"...

**Comment by yar229** [comment]
Если
аккаунт  = `test@mail.ru`
пароль к облаку = `password`
пароль, которым ты хочешь шифровать файлы = `secret`, то
строка будет
`dav://test@mail.ru#_SEP_:password_SEP_secret@127.0.0.1:3332`

3332 нужно поменять на порт, на котором запущен wdmrc, по умолчанию это 801

**Comment by Hunter23071985** [comment]
**yar229**, в целом получилось. Две проблемы:
1) Как добавить в mrc.script
wdmrc.exe --install wdmrc --port 3332 --maxthreads 15
net start wdmrc
ping 127.0.0.1 -n 6 > nul
...
wdmrc.exe --uninstall
2) Как вытащить Test.zip.share.wdmrc на HDD (почему-то он создался в шифрованной папке в Облаке)

**Comment by yar229** [comment]
1. Про скачивание файла по публичной ссылке смотрите туда - https://github.com/yar229/WebDavMailRuCloud/issues/145 , как сделаю, напишу.

2. Про аналоги, которые бы и под WinXP, и с командной строкой не в курсе, к сожалению. 
Официальный [Disk O:](https://disk-o.cloud/) не подходит?
Есть еще [плагин для Total Commander](https://github.com/pozitronik/CloudMailRu)'a, в ТС можно как-то скриптить, но тут уже не помогу.

**Comment by Hunter23071985** [comment]
**yar229**, на счёт скачивания понял, буду ждать.
По поводу wdmrc предлагаю обдумать понижение требований с NetFramework 4.5 до 4.0.
Я бы сказал никаких п[ринципиальных отличий](https://habr.com/post/169029/) 4.5 от 4.0 нет и
среда выполнения у всех NetFramework 4.x (4.0-4.8) одна и та же ([Common Language Runtime 4](https://en.wikipedia.org/wiki/Common_Language_Runtime)).

**Comment by yar229** [comment]
Для скачивания возьмите последний релиз [1.10.1.16](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.16)

Обдумывал. В самом .NET прямо вот принципиально нет. В коде много придётся менять, а я точно не готов потратить на это время. Разве кто форкнет проект и сделает, но это вряяяд ли :)

**Comment by Hunter23071985** [comment]
**yar229**, по поводу .NET Вас понял. Жаль, конечно, но что поделать...
По upload/download - или я что-то не так делаю, или что-то не так работает:
1) При выгрузке Test.zip (185 КБ) в Облаке получается бардак:
помимо .crypt.wdmrc появляется ещё 4 файла - Test.zip.wdmrc.0013 (184 Кбайт), Test.zip (212 байт),
а также Test.zip.share.wdmrc и Test.zip.share.wdmrc.wdmrc.0013.
2) При загрузке по ссылкам из файла Test.zip.share.wdmrc:
- ссылка 2 на Test.zip.wdmrc.0013 (184 Кбайт) не загружается, хотя по размеру это и есть мой архив,
- ссылка 1 на Test.zip (212 байт) загружается, но зачем она нужна вообще не ясно.
Как сделать 2 файла в Облаке, 1 ссылку в файле и чтобы она нормально загружалась?

**Comment by yar229** [comment]
Бардак плановый :) Поскольку надо как-то где-то хранить информацию и иметь к ней быстрый доступ, то 

.crypt.wdmrc - сообщает, что содержимое папки надо шифровать
Test.zip - в нем хранятся данные, нужные для шифрования
Test.zip.wdmrc.0013 - это, собственно, зашифрованное содержимое файла

Когда расшаривается файл, для него создается еще 1 файл с информацией об этом - Test.zip.share.wdmrc.
Поскольку папка шифрованная, то в нем будет лежать инфа о шифровании, а зашифрованное содержимое, соответственно, переедет в Test.zip.share.wdmrc.wdmrc.0013

Вот такие пироги с котятами. В общем, шифрование и расшаривание файлов вместе как-то не особо полезны.
Как вариант, (де)шифруйте файлы чем-то другим при закачивании/скачивании.
Не в курсе вашего сценария использования, поэтому не знаю, что подсказать.

**Comment by Hunter23071985** [comment]
Сценарий - скрипт для выгрузки в Облако и скрипт для загрузки из него.
Выгружаю сам, загружают другие.
Именно поэтому во втором батнике нужно исключить логин и пароль.

**Comment by yar229** [comment]
в общем, всё сложно
исключить логин-пароль не получится (ну или получится, но нескоро)
с шифрованием в вашем кейсе тоже сложно, лучше использовать что-то внешнее, посмотрите в сторону CarotDAV, CyberDuck, wget/wput, curl/gpg

**Comment by Hunter23071985** [comment]
Хорошо...
Согласитесь, что сообщать приватный логин-пароль для скачивания публичной ссылки не логично.
Как и делать в папке 4000 дополнительных файлов для шифрования 1000 основных.

Если поможет, код MegaCMD открыт, там есть и расшаривание ссылки и сквозное шифрование.
Но в Mega 50 ГБ и ~4 ГБ/6 час. с тем же IP, а в Mail 1 ТБ и безлимит по объёму/скорости закачки.
Хотелось бы уже воспользоваться облаком Mail, а то лежит мёртвым грузом. )

Так что буду ждать и надеяться на Вас!

**Comment by yar229** [comment]
Про логин-пароль я уже говорил.
По поводу файликов - там свои глубины, и, поверьте, всё это сделано не просто так.

**Comment by Hunter23071985** [comment]
Охотно верю, что Вы сделали всё возможное на данном этапе. Спасибо за помощь!
И дальнейшего успешного развития проекту!
