### ISSUE TITLE
Unexpected exception - при неверном логине/пароле

### ISSUE THREAD

**Issue by ivang7** [yar229/WebDavMailRuCloud#147]
Клиент - плагин WebDav для Total Commander (Android).
Яндекс ВебДав с некорректной авторизацией выдает окошко ввода пароля.
Здесь же этот случай не обрабатывается, клиенту не отправляется информация о неверной авторизации.

[5]: OAuth: authorizing.
[5]: HTTP:POST:https://o2.mail.ru/token (642 ms)
[5]: Unexpected exception while handling request (method=PROPFIND, url=http://192.168.1.103:8019/
System.AggregateException: Произошла одна или несколько ошибок. ---> System.Exception: OAuth: Error Code=3, Value=invalid username or password, Description=username or password is incorrect
   в YaR.MailRuCloud.Api.Extensions.DtoImportWebBin.ToAuthTokenResult(Result data)
   в YaR.MailRuCloud.Api.Base.Auth.OAuth.<Auth>d__20.MoveNext()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   в YaR.MailRuCloud.Api.Base.Auth.OAuth.<.ctor>b__4_0(AuthTokenResult old)
   в YaR.MailRuCloud.Api.Common.Cached`1.<>c__DisplayClass8_0.<RefreshValueIfNeeded>b__0()
   в System.Lazy`1.CreateValue()
   в System.Lazy`1.LazyInitValue()
   в YaR.MailRuCloud.Api.Common.Cached`1.RefreshValueIfNeeded()
   в YaR.MailRuCloud.Api.Common.Cached`1..ctor(Func`2 valueFactory, Func`2 duration)
   в YaR.MailRuCloud.Api.Base.Auth.OAuth..ctor(HttpCommonSettings settings, IBasicCredentials creds, AuthCodeRequiredDelegate onAuthCodeRequired)
   в YaR.MailRuCloud.Api.Base.Repos.WebM1RequestRepo..ctor(IWebProxy proxy, IBasicCredentials creds, AuthCodeRequiredDelegate onAuthCodeRequired, Int32 listDepth)
   в YaR.MailRuCloud.Api.Base.Repos.RepoFabric.Create()
   в YaR.MailRuCloud.Api.Base.Account..ctor(CloudSettings settings, Credentials credentials)
   в YaR.MailRuCloud.Api.MailRuCloud..ctor(CloudSettings settings, Credentials credentials)
   в YaR.WebDavMailRu.CloudStore.CloudManager.CreateCloud(HttpListenerBasicIdentity identity)
   в YaR.WebDavMailRu.CloudStore.CloudManager.Instance(IIdentity identityi)
   в YaR.WebDavMailRu.CloudStore.Mailru.StoreBase.MailruStore.GetItemAsync(WebDavUri uri, IHttpContext httpContext)
   в NWebDav.Server.Handlers.PropFindHandler.<HandleRequestAsync>d__3.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
---> (Внутреннее исключение #0) System.Exception: OAuth: Error Code=3, Value=invalid username or password, Description=username or password is incorrect
   в YaR.MailRuCloud.Api.Extensions.DtoImportWebBin.ToAuthTokenResult(Result data)
   в YaR.MailRuCloud.Api.Base.Auth.OAuth.<Auth>d__20.MoveNext()<---

**Comment by yar229** [comment]
fixed [1.10.2.2](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.2.2)
