### ISSUE TITLE
Дедлок при монтировании WDMRC через rclone mount

### ISSUE THREAD

**Issue by ivandeex** [yar229/WebDavMailRuCloud#149]
Как воспроизвести (Windows 8.1 amd64):
1. устанавливаем последний WDMRC 1.10.2.2 (.NET 4.5)
2. запускаем службу wdmrc:
    wdmrc.exe --install wdmrc -h http://* -p 8810
    start-service wdmrc
3. устанавливаем последний rclone 1.45
4. добавляем wdmrc в настройки rclone
    запускаем rclone config или добавляем вручную раздел в файл ~/.config/rclone/rclone.conf
    [wdmrc]
    type = webdav
    url = http://127.0.0.1:8810
    vendor = other
    user = username@mail.ru
    pass = supersecret
5. устанавливаем winfsp, чтобы работал rclone mount, отсюда  http://www.secfs.net/winfsp/download/
6. через веб-интерфейс cloud.mail.ru создаём тестовый файл test.txt с  1-3 строками "hello world"
7. монтируем MailRuCloud -> WDMRC -> rclone mount -> локальный диск X:
    открываем терминал, запускаем команду "rclone mount wdmrc: x:"
    команду оставляем висеть
8. открываем второй терминал с cmd.exe и делаем:
      cmd /c type x:\test.txt
    команда зависает (ошибка)
останавливаем (ctrl-c) "rclone mount" и "type test.txt"
что еще было проверено:
- пробуем вывести текст напрямую без монтирования: rclone cat wdmrc:test.txt - работает
- используем вместо cloud.mail.ru+webdav какой-нибудь другой webdav-диск, например disk.yandex.ru - "rclone mount yadisk-webdav: x:" - работает отлично
- на шаге 7 монтировал wdmrc с дополнительными ключиками "rclone mount wdmrc: x: --vfs-cache-mode=full -vvv" - зависание при чтении пропало, всё стало нормально работать.
с опцией "-vvv" rclone печатает, какие webdav-запросы он отправлял. видно, что проблема возникаем в его функции  ChunkedReader, когда она пытается вычитать webdav-файл "по частям". если же запустить с опцией "--vfs-cache-mode=full", то rclone работает иначе: открыла файл, последователно вычитала до конца в кеш, дальше работает только из кеша.
Итого: WDMRC завешивает запрос при webdav-чтении файла "по частям".

**Comment by yar229** [comment]
Спасибо за подробную инструкцию!
Да, печаль какая-то, буду смотреть.

**Comment by ivandeex** [comment]
Ещё комментарий (может, подтолкнёт мысль). Если запустить связку wdmrc+mono+rclone в ubuntu под virtualbox, например, `docker run -p8810:8810 ivandeex/wdmrc:stable; rclone mount wdmrc: ./mnt --daemon; cat mnt/hello.txt` с образом https://github.com/ivandeex/wdmrc-proxy/tree/master/xenial-mono), то дедлока не будет. Однако, интересует именно деплой под Windows. Лог из wdmrc к сожалению не сохранился.

**Comment by yar229** [comment]
На Windows 10 с указанными версиями добился такого поведения только в том случае, если
1. Скачать файл (`cmd /c type x:\test.txt`)
2. Через веб-интерфейс делаем так, чтобы размер файла изменился.
3. Снова скачать файл (`cmd /c type x:\test.txt`)

Проблема в кэшировании свойств каталогов и файлов - rclone и wdmrc их по умолчанию кэшируют на некоторое время и не знают, что файл изменился.

Вижу только вариант с отключением кэширования
* у wdmrc ключ `--cache-listing 0`
* у rclone ключ `--dir-cache-time 0`

@ivandeex , если проблема остаётся, уточните, пожалуйста, как воспроизвести.

**Comment by ivandeex** [comment]
Да, при отключении кэша директорий у любой из программ "type test.xt" более не лочится.
Можно отключить кэш и у обеих сразу, но тогда вывод "dir" очевидно замедляется.

Теперь, когда на игрушечном файле чтение/запись заработала, потестирую связку на более реальных файлах (образы по нескольку гигов). Наверняка, что-то ещё вылезет.
P.S. Я использую именно "cmd /c dir", потому что powershell'овский ls лезет в содержимое файлов,
и они начинают вычитываться, похоже целиком.

Спасибо за воркараунд.
