### ISSUE TITLE
Каким путем/софтом лучше всего бэкапить windows 10 через WebDav

### ISSUE THREAD

**Issue by yeralin** [yar229/WebDavMailRuCloud#153]
Я попытался использовать Duplicati, все хорошо работает, но Duplicati только бэкапит файлы. Яб хотел попробовать бэкапить с помощью родного "Backup and Restore" (но он не поддерживает WebDav и не видит смонтированый диск) или с помощью какого нибудь не родного софта который бы мог снимать полный образ диска (не отдельных файлов) и заливать образ напрямую через WebDav.

**Comment by yar229** [comment]
Родной видит, если подключить диск через [RaiDrive](https://www.raidrive.com/)

Не родной софт при таком подключении диска тоже с большой вероятностью увидит.

**Comment by yeralin** [comment]
Для тех, кто тоже бьется головой о стену.

Нашел рабочий вариант, вместо родного монтирования "Network Drive", используем NetDrive 3. "Backup and Restore" не видит оба, так что я решил использовать "EaseUS Todo Backup" делает тоже самое и даже больше.

For those, who also wants to backup Windows 10 or complete partitions/disks, I found a working combination.

Mount webdev using NetDrive 3 (not built-in Network Drive). Native "Backup and Restore" will not see either, so I used "EaseUS Todo Backup" to perform and upload backups.

**Comment by yar229** [comment]
Странно, вот, смотрю на Win10
![image](https://user-images.githubusercontent.com/5150160/54088032-5bf6b500-436a-11e9-9f53-b9f7c9ad8008.png)

**Comment by yeralin** [comment]
![image](https://user-images.githubusercontent.com/8620461/54088052-f1288800-432f-11e9-943f-ee082b96b497.png)
У меня так :)

**Comment by yar229** [comment]
F: жеж не через RaiDrive замаплен...

**Comment by yeralin** [comment]
M: замаплен через NetDrive 3

Сейчас попробую с RaiDrive тоже. Спасибо за совет :)

**Comment by yeralin** [comment]
![image](https://user-images.githubusercontent.com/8620461/54088120-c12db480-4330-11e9-83d6-010b761fd384.png)
Все равно не видит. Может моя проблема, что я пытаюсь использовать "Backup and Restore (Windows 7)" вместо новой.

**Comment by yeralin** [comment]
Да родная Windows 10 backup видит только RaiDrive:

![image](https://user-images.githubusercontent.com/8620461/54088156-6d6f9b00-4331-11e9-9c93-d9ed32f7ce21.png)
