### ISSUE TITLE
фичэ риквест ;-)

### ISSUE THREAD

**Issue by admzzz** [yar229/WebDavMailRuCloud#155]
добавить в wdmrc 2 команды синхронизации (или одну, но с указанием откуда-куда): всё из облака в локальную папку с перезаписыванием/удалением без вопросов и всё из локальной папки в облако (аналогично).

просто вариант "сперва удалить всё, потом копировать" иногда избыточен/дорог.

**Comment by yar229** [comment]
Это "клиентская" фича, вот тут #144 есть пример для [WinSCP](https://winscp.net/)
С вероятностью 100% есть и другие клиенты с поддержкой синхронизации туда-сюда.
