### ISSUE TITLE
2FA plugin: read code from file

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#156]
К имеющимся плагинам считывания кода из консоли и формы добавить плагин, который будет мониторить на предмет изменений файл и брать код оттуда.

@ziceptor

> В трее пусть болтается отдельное приложение, скидывающее код в файл. Сервис "держит руку на пульсе".. проверяет файл.
Или приложение напрямую взаимодействует с сервисом.

@yar229 

> Это да, просто надо написать.
Давайте сделаем так - не самый удобный, но самый простой вариант #156

**Comment by yar229** [comment]
@ziceptor, если устроит такой вариант - попробуйте [1.10.5.5](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.5.5), напишите, как-что.

В файле `wdmrc.config` заменить `<TwoFactorAuthHandler Name = "AuthCodeConsole"></TwoFactorAuthHandler>` на
```
  <TwoFactorAuthHandler Name = "AuthCodeFile">
    <Param Name = "Directory" Value = "d:"/>
    <Param Name = "FilenamePrefix" Value = "wdmrc_2FA_"/>
  </TwoFactorAuthHandler>
```
В данном примере для пользователя `test@mail.ru` появится файл `d:\wdmrc_2FA_test@mail.ru`, в который надо записать полученный код авторизации.

**Comment by ziceptor** [comment]
Работает. Вариант устраивает более чем :) Большое спасибо!

**Comment by ziceptor** [comment]
Файл wdmrc_2FA_*@mail.ru, после ввода кода и доступа к облаку, не удаляется автоматом по какой-то необходимой причине?

**Comment by yar229** [comment]
Прекрасно! :)
Файл оставался просто так, теперь удаляю, см. [1.10.5.7](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.5.7)

![image](https://user-images.githubusercontent.com/5150160/55511258-cb5d7d00-5668-11e9-91c4-69c1c5675e29.png)
