### ISSUE TITLE
Мониторинг изменений в облаке?

### ISSUE THREAD

**Issue by ilyaroot** [yar229/WebDavMailRuCloud#157]
Поясните темному, изменения в Облаке (через web-интерфейс, другие клиенты) отслеживаются? Если да, можно простенький пример кода ожидания хотя бы события удаления файла, создания нового, пришедшего с серверов облака.

Просто mail.ru окончательно прикрыли свой клиент синхронизации под Linux и есть идея написать свой.

**Comment by yar229** [comment]
Через тот, по которому общается web-морда (в проекте WebV2, WebM1) - нет.

Через протокол мобильного клиента (в проекте WebBin) - в каком-то смысле да - отправляешь определенный запрос и в ответ получаешь не всё, а только произошедшие изменения.

Не расковыривал пока формат этого запроса, вряд ли буду делать это в ближайшее время.

**Comment by ilyaroot** [comment]
А можно хотя бы пример такого запроса, наименование метода? Чтобы знать, куда ковырять.

**Comment by yar229** [comment]
\MailRuCloud\MailRuCloudApi\Base\Requests\WebBin\ListRequest.cs 

Запрос на листинг каталога,  "код" - Operation.FolderList = 117
Там в ответе среди прочего приходит версия данных.

Нужно помониторить, выяснить код для запроса измененных данных, отправить его с (какими-то) параметрами и номером версии, полученным ранее.
В ответ приедет (если что-то изменилось) новый номер версии данных и список изменений.




Запрос

**Comment by ilyaroot** [comment]
Предыдущая версия программы синхронизации (которая была до Диск-О и до сих пор работает) узнавала о новых файлах мгновенно. Явно не дергала сервер каждые 5 секунд. Наверное, она как-то поддерживала постоянное соединение с сервером, Websocket или Long Polling или что-то в этом роде.

Но дергать сервер тоже неплохо, при изменениях можно просто вызывать
rclone sync cloud-mail-ru:/ local-folder/ -P
и готова простенькая синхронизация при изменениях на сервере.

Спасибо, буду разбираться.

**Comment by yar229** [comment]
> Предыдущая версия программы синхронизации (которая была до Диск-О и до сих пор работает на винде) узнавала о новых файлах мгновенно. Явно не дергала сервер каждые 5 секунд. Наверное, она как-то поддерживала постоянное соединение с сервером, Websocket или Long Polling или что-то в этом роде.

Не ставил ее, не трогал, вполне вероятно, что так и есть.

В добрый час :)

**Comment by ilyaroot** [comment]
Если что, вот предыдущая версия, которая до сих пор рабочая:
http://clouddl.mail.ru/windows/Mail.Ru_Cloud.exe
В ее настройках в качестве прокси можно указать Fiddler и смотреть запросы в реальном времени.

**Comment by yar229** [comment]
Спасибо, буду иметь ввиду
