### ISSUE TITLE
Не работает консольная утилита convert из пакета ImageMagick

### ISSUE THREAD

**Issue by 1690147** [yar229/WebDavMailRuCloud#158]
При запуске получаю такой выхлоп:
```
$ mkdir lowres; for f in *.jpg; do convert -quality 90 -resize 1920x1080 "$f" "lowres/${f%.jpg}-1080.jpg"; done
convert: unable to open image `lowres/IMG_20190408_195018-1080.jpg': File exists @ error/blob.c/OpenBlob/2761.
convert: unable to open image `lowres/IMG_20190408_195036-1080.jpg': File exists @ error/blob.c/OpenBlob/2761.
```
На диске от Яндекса такой проблемы нет.

Монтирую через davfs2.

**Comment by yar229** [comment]
У меня вот так вот всё отработало 

```
mkdir lowres; for f in *.jpg; do convert "$f" -quality 90 -resize 1920x1080 "lowres/${f%.jpg}-1080.jpg"; done
```
```
convert -version
Version: ImageMagick 7.0.8-41 Q16 x86_64 2019-04-23 https://imagemagick.org
```

**Comment by 1690147** [comment]
Как и было сказано на главной странице:

> Mount with davfs2
> * `mkdir /mnt/` * edit `/etc/davfs2/davfs2.conf` set `use_locks 0` * `sudo mount --rw -t davfs http://: /mnt// -o uid=` 

Нужно было добавить `use_locks 0` в `/etc/davfs2/davfs2.conf` После этого проблема исчезла.

**Comment by yar229** [comment]
О, спасибо, сам что-то не догадался
