### ISSUE TITLE
Ошибки при создании вложенных директорий через rclone

### ISSUE THREAD

**Issue by u1138** [yar229/WebDavMailRuCloud#159]
Команда `rclone mkdir mailrucloud:dir1/dir2` вызывает ошибки, если dir1 не создана заранее. Если dir1 есть, rclone отрабатывает успешно.

WebDavMailRuCloud запускался на Linux.

**Comment by yar229** [comment]
fixed @ [1.10.7.12](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.7.12)
