### ISSUE TITLE
Корпоративная почта на mail.ru

### ISSUE THREAD

**Issue by linegor** [yar229/WebDavMailRuCloud#161]
Добрый день, не подключается диск если почта на mail.ru привязана к домену.
Хотя утилита диск О: спокойно подключает диск, например stroy@dekopro.net

**Comment by yar229** [comment]
Хм... Вроде я себе что-то такое заводил. Постараюсь вспомнить и опробовать. Но неспешно, лето! :)

**Comment by yar229** [comment]
Речь идёт про https://biz.mail.ru/mail/, я правильно понимаю?
Завел почту на своём домене (а-ля me@mydomain.ru), выдали на неё 8Гб в облаке, залогинился, все нормально вроде.

**Comment by yar229** [comment]
Нельзя залогиниться под синонимом, только под основным именем пользователя

![image](https://user-images.githubusercontent.com/5150160/67198738-41101700-f408-11e9-8b27-a18e18a7058a.png)
