### ISSUE TITLE
Очень медленный отклик

### ISSUE THREAD

**Issue by akrush24** [yar229/WebDavMailRuCloud#162]
Вот сколько у меня занимает листинг корневого каталога 

```
$ time ls -l
total 23137
....

real    1m38.217s
user    0m0.001s
sys     0m0.013s
```

При это одно ядро загружено на 100%. процессом mono. (как на счет многопоточности, для ускорения процесса?)
Может быть есть пути как-то ускорить данный процесс? 

запускаю так
```sudo mono wdmrc.exe -p 801 ```

пробовал с ключом --cache-listing-depth [2|3], с ним становится еще хуже,  и вовсе  не монтируется.

```/sbin/mount.davfs: connection timed out two times;
trying one last time

/sbin/mount.davfs: server temporarily unreachable;
mounting anyway```

**Comment by yar229** [comment]
В логе там миллион запросов к облаку?

**Comment by akrush24** [comment]
да, запросов сыпятся много

**Comment by afwn90cj93201nixr2e1re** [comment]
Может просто отключить логирование? Тогда stdout не будет жрать cpu. @yar229

**Comment by yar229** [comment]
Скорее, это из-за того, что давфс пытается получить данные по каждой папке/файлу отдельно, соответственно, охрененное кол-во запросов. 
За давностью уже непонятно, так ли это.
С кэшированием `--cache-listing-depth` с тех пор были некоторые изменения, так что надо проверять снова.

**Comment by yar229** [comment]
> Может просто отключить логирование? Тогда stdout не будет жрать cpu.

Отключить логирование можно в wdmrc.config
```
    <root>
      <level value="ALL"/>
      <appender-ref ref="ColoredConsoleAppender"/>
      <!-- <appender-ref ref="RollingLogFileAppender"/>  -->
    </root>
```
заменить на
```
    <root>
      <level value="ALL"/>
      <!-- <appender-ref ref="ColoredConsoleAppender"/>  -->
      <!-- <appender-ref ref="RollingLogFileAppender"/>  -->
    </root>
```
