### ISSUE TITLE
Названия каталогов.

### ISSUE THREAD

**Issue by EternoxS** [yar229/WebDavMailRuCloud#164]
Обнаружилась проблема - если на облаке есть каталоги содержащие символы расширенной латиницы (например "‎Adršpašské skály, CZ"), то возникают частичные проблемы доступа - можно получить список каталогов того же уровня, можно получить список файлов в "проблемном" каталоге, но операции с файлами - открыть, скопировать, записать новый в этот каталог - увы, не выполняются.

**Comment by yar229** [comment]
Версия? Линукс/виндоус? Какой клиент?

Именно с этим названием не воспроизвелось.
Если возможно, пришлите листинг каталога.
Можно на почту yar229@yandex.ru

**Comment by EternoxS** [comment]
Прошу прощения за долгий ответ.
Проведя небольшое расследование (win10x64/mint19.x, последние версии), выяснил, что расширенная латиница тут не при чем. Все дело было в "запятая" в названии каталога (создавалось через веб).

**Comment by yar229** [comment]
С запятой тоже не могу воспроизвести...
