### ISSUE TITLE
Бинарные релизы для более ранних версий .Net?

### ISSUE THREAD

**Issue by positron96** [yar229/WebDavMailRuCloud#166]
Есть ли возможность делать релизы для более ранних версий .NET? У меня даже в последней десятке (без каких-либо установленных средств разработки) стоит .NET 4.0 и бинарник не запускается.

```
  WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.10.8.1
  yar229@yandex.ru
[1]: OS Version: Microsoft Windows NT 6.2.9200.0
[1]: CLR: .NET Framework 4.0.30319.42000
[1]: User interactive: True
[1]: Version: 1.10.8.1
[1]: Max threads count: 5
[1]: Cloud protocol: WebM1Bin
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1

Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.HttpListener..ctor()
   at YaR.CloudMailRu.Console.Payload.Run(CommandLineOptions options)
   at YaR.CloudMailRu.Console.Program.<>c.<Main>b__1_0(CommandLineOptions options)
   at YaR.CloudMailRu.Console.Program.Main(String[] args)

```

**Comment by pasha-zzz** [comment]
> OS Version: Microsoft Windows NT 6.2.9200.0

Это Windows 8.0, даже не 8.1. На ней голой идет 4.0. Но кто мешает поставить 4.5.
А в самой предпоследней десятке (1903) искаропки 4.8

**Comment by positron96** [comment]
Ну тогда значит, приложение как-то неправильно определяет версию, потому что это точно десятка.

````
C:\Users\positron\Downloads\WebDAVCloudMailRu-1.10.8.1-dotNet461>ver

Microsoft Windows [Version 10.0.18362.476]

C:\Users\positron\Downloads\WebDAVCloudMailRu-1.10.8.1-dotNet461>wdmrc
  WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.10.8.1
  yar229@yandex.ru
[1]: OS Version: Microsoft Windows NT 6.2.9200.0
[1]: CLR: .NET Framework 4.0.30319.42000
[1]: User interactive: True
[1]: Version: 1.10.8.1
[1]: Max threads count: 5
[1]: Cloud protocol: WebM1Bin
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
````

**Comment by positron96** [comment]
Собственно, стоит именно 4.8:
```
C:\Users\positron\Downloads\WebDAVCloudMailRu-1.10.8.1-dotNet461>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc
Microsoft (R) Visual C# Compiler version 4.8.3752.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

warning CS2008: No source files specified
error CS1562: Outputs without source must have the /out option specified
```
папка называется 4.0.30319, но это [нормально](https://superuser.com/questions/522027/where-is-net-framework-4-5-directory-located), вроде

**Comment by yar229** [comment]
Проверьте, не установили ли вы запуск в режиме совместимости

**Comment by pasha-zzz** [comment]
Да, на 10ке вывод именно такой, но при этом все работает...
Порт пробовали менять? Например:
`
wdmrc -p 8443 -h "http://*"
`

**Comment by pasha-zzz** [comment]
>   WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
>   v.1.10.8.1
>   yar229@yandex.ru
> [1]: OS Version: Microsoft Windows NT 6.2.9200.0
> [1]: CLR: .NET Framework 4.0.30319.42000
> [1]: User interactive: True
> [1]: Version: 1.10.8.1
> [1]: Max threads count: 5
> [1]: Cloud protocol: WebM1Bin
> [1]: Cache listings, sec: 30
> [1]: List query folder depth: 1
> [1]: WebDAV server running at http://*:8443/
> [5]: OPTIONS:http://127.0.0.1:8443/:127.0.0.1:8443 - Start processing
> [5]: OPTIONS:http://127.0.0.1:8443/:127.0.0.1:8443 - Finished processing (5ms, HTTP result: 200)
> [6]: PROPFIND:http://127.0.0.1:8443/:127.0.0.1:8443 - Start processing
> [6]: Cloud instance created for *******@mail.ru
> [6]: OAuth: authorizing.
> [6]: HTTP:POST:https://o2.mail.ru/token (415 ms)

**Comment by positron96** [comment]
Нет, запускал не в режиме совместимости, просто распаковал и запускал. 

Но! 
Сейчас не могу воспроизвести эту ошибку. Все работает нормально. То ли винда обновилась и что-то исправилось, то ли звезды повернулись. Когда зарепортил баг, проблема стабильно воспроизводилась, сейчас все работает.

**Comment by positron96** [comment]
Пробовал сейчас запустить два экземпляра на одном порту - получаю другую ошибку при старте второго экземпляра: 
```
Unhandled Exception: System.Net.HttpListenerException: Failed to listen on prefix 'http://127.0.0.1:801/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at YaR.CloudMailRu.Console.Payload.Run(CommandLineOptions options)
   at YaR.CloudMailRu.Console.Program.<>c.<Main>b__1_0(CommandLineOptions options)
   at YaR.CloudMailRu.Console.Program.Main(String[] args)

```
Если запускать не от администратора, то тоже ошибка другая.
Т.е. дело не в возможности создания сокета.

Похоже на вот это: https://stackoverflow.com/questions/45899696/why-i-cant-use-httplistener-in-my-windows-10-computer-system-platformnotsuppo

**Comment by yar229** [comment]
На один порт низзя.

Если я правильно понимаю, вы запускаете два экземпляра, чтобы использовать два разных логина.
Есть следующие варианты:
* если вы планируете подключать диски командой `net use`, то запускайте с ключом `--port 801,802`. Соответственно, первый диск на порт 801 вешайте, второй на порт 802.
* если вы НЕ планируете подключать диски командой `net use`, то достаточно одной копии на одном порту, все будет работать.

**Comment by pasha-zzz** [comment]
> Есть следующие варианты
Есть еще, если на локалхосте сервис... Больше 16 млн адресов локалхоста.

**Comment by positron96** [comment]
Нет-нет, я просто для эксперимента запустил два экземпляра, чтоб посмотреть, не вызвана ли эта ошибка занятым портом.
