### ISSUE TITLE
Missing domain part

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#170]
YaDisk... Login to disk:
[6]: Missing domain part (mail, @inbox, @bk, @list) in login, file and folder deleting will be denied
Domain @yandex.ru but there are many mirror domains (@ya.ru, @yandex.com, @yandex.by, @yandex.kz, @yandex.ua)

**Comment by pasha-zzz** [comment]
And dirs deletion (when they have files/other dirs) is very-very long... Deleting fast but dir stays and slowly deleting in background. This operation async only?

**Comment by yar229** [comment]
fixed cca2d83d64b314e9eac94a105ea3b60f8ecf6bd0
