### ISSUE TITLE
Dirs deletion (when they have files/other dirs) is very-very long... Deleting fast but dir stays and slowly deleting in background. This operation async only?

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#171]
And dirs deletion (when they have files/other dirs) is very-very long... Deleting fast but dir stays and slowly deleting in background. This operation async only?

_Originally posted by @pasha-zzz in https://github.com/yar229/WebDavMailRuCloud/issues/170#issuecomment-566965082_

**Comment by yar229** [comment]
fixed [1.11.0.3](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.3)

**Comment by pasha-zzz** [comment]
Anyway after deletion folder stays. Folder with ~10-15 files stays for 15-20 secs (if  I press Ctrl+R many times)

**Comment by yar229** [comment]
fixed [1.11.0.7](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.7)

**Comment by yar229** [comment]
Same bug with rename

**Comment by yar229** [comment]
fixed [1.11.0.8](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.8)

**Comment by yar229** [comment]
Same bug with move (GoodSync)

**Comment by yar229** [comment]
fixed [1.11.0.10](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.10)
