### ISSUE TITLE
Бесконечные предупреждения "executable is not supported on item" при монтировании через davfs2

### ISSUE THREAD

**Issue by BrainNull** [yar229/WebDavMailRuCloud#173]
Log забит вот этим о каждом файле:

`[Thread Pool Worker]: Property {http://apache.org/dav/props/}executable is not supported on item`

**Comment by yar229** [comment]
fixed [1.11.0.9](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.9)
