### ISSUE TITLE
500 при закачке на .NET 4.6.2

### ISSUE THREAD

**Issue by wave-blessed** [yar229/WebDavMailRuCloud#181]
Привет.
Какое-то время я эти облака не трогал, а тут понадобилось. На новом месте.
Win7x86 (ну, так вышло). .NET 4.6.2. Установил `"C:\Program Files\wdmrc\wdmrc.exe" --install wdmrc -p 5050` последнюю версию. И обнаружил, что скачиваются файлы без вопросов, а вот при закачке клиент (FAR NetBox и TotalCmd WebDav) говорит, что — 500.
Остановил службу, запустил в консоли, увидел, что там что-то про ошибку с Assembly… Короче, обновил фреймворк до 4.8 — заработало нормально. На всякий случай сообщаю.

**Comment by yar229** [comment]
Да, действительно, есть такая печаль при использовании .NET HttpClient.
Спасибо за информацию, отражу в ридми.
