### ISSUE TITLE
Привет, не могу к яндексу подключиться.

### ISSUE THREAD

**Issue by jonbv13** [yar229/WebDavMailRuCloud#182]
Прошу помощи как подключить ЯД пишет не верный логин или пароль?
установил как службу
`"C:\WebDAVCloudYa\wdmrc.exe" --host http://0.0.0.0 --port 803,804 --protocol YadWeb --install WDMRCY
Pause`
Еще вопрос можно два протокола на одну службу включить?

**Comment by yar229** [comment]
> установил как службу
Pause не надо
`"C:\WebDAVCloudYa\wdmrc.exe" --host http://0.0.0.0 --port 803,804 --protocol YadWeb --install WDMRCY`

> Прошу помощи как подключить ЯД пишет не верный логин или пароль?
Без логов сложно что-то сказать

> Еще вопрос можно два протокола на одну службу включить?
Нет, одну службу для мейл.ру, другую для Я.Диска.
На всякий случай - порты у служб должны быть разные.
Когда-нибудь сделаю одну.

**Comment by jonbv13** [comment]
Где логи смотреть?

а две службы из разных папок и с разными именами, портами?

![Скриншот 19-02-2020 121212](https://user-images.githubusercontent.com/61148532/74810436-2cd61b00-5311-11ea-973f-06ca9ecb9813.jpg)

**Comment by jonbv13** [comment]
![Скриншот 19-02-2020 121806](https://user-images.githubusercontent.com/61148532/74810924-4035b600-5312-11ea-9a43-98855bf56403.jpg)
Это к ЯД

**Comment by yar229** [comment]
Остановите службу, если она установлена
`net stop WDMRCY`

Запустите wdmrc в отдельном окне без установки службы
`"C:\WebDAVCloudYa\wdmrc.exe" --host http://0.0.0.0 --port 803,804 --protocol YadWeb`

Попробуйте подключить диск.

Пришлите то, что пишется в окне wdmrc.

Лучше на почту.

**Comment by jonbv13** [comment]
-- С Уважением,Безмельницин Евгений +79191401367jonbv@mail.ru   27.02.2020, 13:26, "YaR" <notifications@github.com>:Остановите службу, если она установленаnet stop WDMRCYЗапустите wdmrc в отдельном окне без установки службы"C:\WebDAVCloudYa\wdmrc.exe" --host http://0.0.0.0 --port 803,804 --protocol YadWebПопробуйте подключить диск.Пришлите то, что пишется в окне wdmrc.Лучше на почту.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jonbv13** [comment]
Прошу прощения затупил. работает из командной строки. ошибок нет -- С Уважением,Безмельницин Евгений +79191401367jonbv@mail.ru   27.02.2020, 13:26, "YaR" <notifications@github.com>:Остановите службу, если она установленаnet stop WDMRCYЗапустите wdmrc в отдельном окне без установки службы"C:\WebDAVCloudYa\wdmrc.exe" --host http://0.0.0.0 --port 803,804 --protocol YadWebПопробуйте подключить диск.Пришлите то, что пишется в окне wdmrc.Лучше на почту.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yar229** [comment]
Давайте с чистого листа.

* Запустите `cmd` под администратором
* `c:\`
* `cd C:\WebDAVCloudYa`
* `net stop WDMRCY`
* `wdmrc.exe --uninstall WDMRCY`
* `wdmrc.exe --host http://0.0.0.0 --port 803,804 --protocol YadWeb --install WDMRCY`
* `net start WDMRCY`

**Comment by jonbv13** [comment]
Огромное Вам спасибо. Все заработало, Новая установка виндовс на ВМ , все с нуля  все работает.    винда корявая на моем ноуте работал только маил, хотел яндекс поставить ( не завелось) теперь и маил не работает. Еще раз спасибо теперь дождаться докер с двумя сервисами и прям в NAS запихнуть -- С Уважением,Безмельницин Евгений +79191401367jonbv@mail.ru   28.02.2020, 17:23, "YaR" <notifications@github.com>:Давайте с чистого листа.Запустите cmd под администраторомc:\cd C:\WebDAVCloudYanet stop WDMRCYwdmrc.exe --uninstall WDMRCYwdmrc.exe --host http://0.0.0.0 --port 803,804 --protocol YadWeb --install WDMRCYnet start WDMRCY—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
