### ISSUE TITLE
Не походит пароль со спецсимволами

### ISSUE THREAD

**Issue by Rootdiv** [yar229/WebDavMailRuCloud#183]
При использовании протокола для подключения к яндексу, пароль со спецсимволами не проходит, всё время ошибка `Error while handling request (method=PROPFIND, url=http://127.0.0.1:801/ Unauthorized: YadAuthPasswordRequest errors: password.not_matched`. Если поставить алфавитно-цифровой пароль, то всё подключается, а я крайне редко использую такие пароли.
Команда запуска dotnet ~/WebDAVCloudMailRu-1.11.0.15-dotNetCore30/wdmrc.dll -h http://127.0.0.1/ -p 801 --protocol YadWeb
Спецсимволы с которыми проверялся пароль `+-*%`

**Comment by yar229** [comment]
fixed [1.11.0.16](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.16)

**Comment by yar229** [comment]
fixed [1.11.0.16](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.16)
