### ISSUE TITLE
.NET Core 3.1 migration

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#184]
Its time to migrate from 3.0 (which reaches EOS):

![image](https://user-images.githubusercontent.com/8224786/76053727-33a29600-5f7f-11ea-88e1-e60b6e0945b3.png)

**Comment by yar229** [comment]
It runs under 3.1. Maybe I'll rename distrib file :)

**Comment by pasha-zzz** [comment]
And it requires .NET Core SDK, Runtime is insufficient?
And is it possible install as Win service with .NET Core?

**Comment by afwn90cj93201nixr2e1re** [comment]
Может тогда пора бы уже в release добавить еще и прямые ссылки на файлы? Ты ведь выгружаешь артифакты и так. Почему бы не сделать статичный файл WindowsCompitable/LinuxCompitable, которые первой строкой будут содержать ссылку на только что загруженный артифакт, а второй строкой команду запуска, а?
Помочь?
Примешь PR?

@yar229
