### ISSUE TITLE
Падения на версии 1.11.0.16

### ISSUE THREAD

**Issue by skipik** [yar229/WebDavMailRuCloud#186]
На версии 1.11.0.16 пытаюсь подключиться к облаку Mail.ru и получаю стабильные падения.
Откат на 1.11.0.15 помогает.
Запускаю таким батником:
```
rem пристрелить сервер, если уже запущен
taskkill /im wdmrc.exe

rem запускаем сервер
start "WebDAV Cloud Mail.Ru" wdmrc.exe -p 3332

rem подождем, пока запустится
ping 127.0.0.1 -n 6 > nul

rem если диск V: уже подключен - отключим
net use V: /DELETE

rem подключаем облако как диск V:
rem net use V: http://127.0.0.1:3332 password /USER:user@list.ru
```
Куда вам можно дампы отправить? Я не хочу их публично выкладывать, вдруг они содержат пару логин\пароль.

**Comment by yar229** [comment]
yar229@yandex.ru

**Comment by skipik** [comment]
Ок, отправил.

**Comment by yar229** [comment]
Скачайте еще раз релиз, я там сначала пару файликов забыл вложить

**Comment by skipik** [comment]
Перекачал - теперь порядок, спасибо большое!
