### ISSUE TITLE
Копирование файлов в mail cloud возможно только если при установке службы использовалась команда "--use-locks false"

### ISSUE THREAD

**Issue by gegemon2012** [yar229/WebDavMailRuCloud#192]
Вот собственно и суть проблемы.

**Comment by yar229** [comment]
Не могу воспроизвести.
Дайте больше информации.
ОС, версия, .нет/коре? 
Возможно,копирование не выполняется только в каталог с определенным именем, определенного файла?

**Comment by gegemon2012** [comment]
Windows 7 sp1 x64, net framework 4.8, имя каталога "Записать". Не создаются любые файлы но удаляются файлы и папки. Создаются папки. Версия вашей программы 1.11.0.23.

**Comment by yar229** [comment]
Спасибо за инфу.
Гм... Какая странная штука. Вроде никаким боком не должно.
Постараюсь посмотреть, но не быстро.

**Comment by yar229** [comment]
Имя пользователя указываете полностью?
Т.е. не просто "myname", а "myname@mail.ru"?

**Comment by gegemon2012** [comment]
Да, полностью. Я и не знал что его можно указать не полностью...

**Comment by yar229** [comment]
попробуйте [1.11.0.24](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.24)
