### ISSUE TITLE
get actual wdmrc version by command line

### ISSUE THREAD

**Issue by alexyr** [yar229/WebDavMailRuCloud#198]
Now it prints 1.0.0:

<pre>
# dotnet wdmrc.dll --version
wdmrc 1.0.0

# dotnet wdmrc.dll --help
wdmrc 1.0.0
yar229@yandex.ru

  -p, --port               (Default: 801) WebDAV server port

  -h, --host               (Default: http://127.0.0.1) WebDAV server host, including protocol

  --maxthreads             (Default: 5) Maximum concurrent connections to cloud

  --user-agent             "browser" user-agent

  --install                install as Windows service with name

  --install-display        display name for Windows service

  --uninstall              uninstall Windows service

  --service                (Default: false) Started as a service

  --protocol               (Default: WebM1Bin) Cloud protocol

  --cache-listing          (Default: 30) Cache folders listing, sec

  --cache-listing-depth    (Default: 1) List query folder depth

  --proxy-address          (Default: ) Proxy address i.e. http://192.168.1.1:8080

  --proxy-user             (Default: ) Proxy user

  --proxy-password         (Default: ) Proxy password

  --use-locks              (Default: false) locking feature

  --help                   Display this help screen.

  --version                Display version information.
</pre>

**Comment by yar229** [comment]
done [1.11.0.30](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.30)
