### ISSUE TITLE
Error: 500 Internal Server Error (не загружает на облако)

### ISSUE THREAD

**Issue by NewSky13** [yar229/WebDavMailRuCloud#199]
**ОС, версия wdmrc:** Win7x64, 1.11.0.30, на двух ПК.
**Использование:** Total Commander, GoodSync
**Проблема:** Файл не загружается в облако. Точнее: В облако заходит, файлы видит, файлы скачиваются, файл "загружается", но как только индикатор загрузки доходит до 100% (при использовании обеих программ) вылетает ошибка: Error: 500 Internal Server Error и на облаке обнаруживается одноименный файл весом 2 байта
Несколько лет (со дня появления WebDavMailRuCloud) настроена синхронизация с 16 облаками, всё работает как часы, и вот 11.09.2020 получил такое. Сразу проверил на втором ПК, та-же история. Стояла версия 1.11.0.20, с ней то-же самое. Попробовал через плагин для TC cloud.mail.ru  - то-же самое, читает, скачивает, но не загружает. Испугался, что Мейловцы совсем перекрыли кислород, но, обновив cloud.mail.ru из Master, о чудо, загрузка на облако пошла. По этому, очень надеюсь, что и ваш замечательный инструмент вернётся к работе!

**Comment by yar229** [comment]
Спасибо за комплимент :)

Проверяйте [1.11.0.31](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.31)
