### ISSUE TITLE
Снимите защиту от записи

### ISSUE THREAD

**Issue by kla-25** [yar229/WebDavMailRuCloud#200]
Всем привет.
Я использую RaiDrive  для подключения маилрушных дисков в компе через wdmrc. Долго не запускал. Вчера включил и не смог ничего закинуть в облако, выдает "Снимите защиту от записи". Прописал логин без "@mail.ru", не коннектится (статья одна попалась, в которой писалось что якобы подключившись  по логину без "@mail.ru", облако соединяется в режиме чтения только).
Попробовал через raidrive подрубиться (они сделали маилру у себя), запись до 2гигов работает.
Хотелось бы вылечить wdmrc )
p.s. яндекс работает файл более 4 гигов записался.

**Comment by yar229** [comment]
Добрый день
Версия wdmrc последняя, [1.11.0.31](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.31)?

**Comment by kla-25** [comment]
Извиняюсь за задержку с ответом.
Версия 1.11.0.30. Сейчас установил 1.11.0.31 и попробовал. Все работает. Файл почти 5 гигов тоже записался...хотя акк на майле бесплатный.
Спасибо вам.
