### ISSUE TITLE
Есть публичная ссылка на файл, как узнать его MailRu Хеш?

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#202]
> 2\. Есть публичная ссылка на файл, как узнать его MailRu Хеш?

Вынесу в отдельную задачу, подумаю как-нибудь

_Originally posted by @yar229 in https://github.com/yar229/WebDavMailRuCloud/issues/196#issuecomment-695066982_

**Comment by yar229** [comment]
Вот таким методом, не вижу пока более правильного пути.

В версии [1.12.1.0](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.12.1.0)

* прилинковать файл: `>>link https://cloud.mail.ru/public/2G6g/6u5F2tRWX`
* в текущей папке появится `picture.jpg`
* выполнить `>>rlist picture.jpg`
* появится файл `picture.jpg.wdmrc.list.lst`. В нем - свойства файла, среди них - хэш

**Comment by yar229** [comment]
Kazimir, [12.09.20 10:41]
> хеши с публичных ссылок я научился тырить прямо из консоли браузера
они хранятся в массиве объектов cloudSettings.params.serverSideFolders.folder.list
Тыкаю F12 и забиваю в консоль браузера однострочник 
`copy(cloudSettings.state.id+"\r\n"+ cloudSettings.params.serverSideFolders.folder.list.map(e=>e.hash+':'+e.size+':\''+e.name+'\'').join("\r\n"))`

**Comment by kybyx** [comment]
> * выполнить `>>rlist picture.jpg`
с файлами первого уровня всё впорядке но во вложеных папках в байты разделяются лишними знаками тире которые не нужны на самом деле.
> /test/SamplesImages/kanzas/fields/1395578-wheat.jpg	933723	2020.10.01 03:56:31	9B-8B-B5-0C-00-05-CD-E2-40-94-50-F0-23-84-06-40-60-A7-5F-29	-

**Comment by kybyx** [comment]
С моей картинкой не заработало

> >>link https://cloud.mail.ru/public/2zsa/HLxiaC86j
>>rlist Omaha.jpg

Error creating Folder >>rlist Omaha.jpg
~~~~~~~~~~~~~~~~~~Исключение вебдавэмулятора~~~~~~~~~~~~~~~~~~~~
[11]: MKCOL:http://127.0.0.1:801/test/%3E%3Erlist%20Omaha.jpg:127.0.0.1:801 - St
art processing
[11]: HTTP:POST:https://cloud.mail.ru/api/m1/folder?access_token=3aa5406a1bde795
6985b18336694f46b4cb4272c37363830&offset=0&limit=2147483647 (300 ms)
[11]: Unexpected exception while handling request (method=MKCOL, url=http://127.
0.0.1:801/test/%3E%3Erlist%20Omaha.jpg, source=127.0.0.1:801
System.AggregateException: One or more errors occurred. ---> System.NullReferenc
eException: Object reference not set to an instance of an object.
   at YaR.Clouds.SpecialCommands.Commands.ListCommand.<Execute>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at YaR.Clouds.WebDavStore.CustomHandlers.MkcolHandler.<HandleRequestAsync>d__
0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
---> (Inner Exception #0) System.NullReferenceException: Object reference not se
t to an instance of an object.
   at YaR.Clouds.SpecialCommands.Commands.ListCommand.<Execute>d__4.MoveNext()<-
--
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~Среда~~~~~~~~~~~~~~~~~~~~~~~~
[1]: OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
[1]: CLR: .NET Framework 4.0.30319.42000
[1]: User interactive: True
[1]: Version: 1.12.1.0
[1]: Using proxy:
[1]: Max threads count: 5
[1]: Cloud protocol: WebM1Bin
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
[1]: Use locks: False
[1]: Start as service: False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by kybyx** [comment]
> * прилинковать файл: `>>link https://cloud.mail.ru/public/2G6g/6u5F2tRWX`
> * в текущей папке появится `picture.jpg`
> * выполнить `>>rlist picture.jpg`
> * появится файл `picture.jpg.wdmrc.list.lst`. В нем - свойства файла, среди них - хэш

Первый раз получилось повторить это
А вот на второй раз уже на другом аккаунте не вышло - ругается на ошибку
https://i.imgur.com/caHViyu.png

**Comment by kybyx** [comment]
> Тыкаю F12 и забиваю в консоль браузера однострочник
> `copy(cloudSettings.state.id+"\r\n"+ cloudSettings.params.serverSideFolders.folder.list.map(e=>e.hash+':'+e.size+':\''+e.name+'\'').join("\r\n"))`

Для одиночных файлов это работает а вот для папок нет, если начать руками  открывать папки то нужно обновлять страницу иначе хеши будут undefined

**Comment by yar229** [comment]
> Первый раз получилось повторить это
> А вот на второй раз уже на другом аккаунте уже не вышло - после рлиста ругается
> https://i.imgur.com/caHViyu.png
> Однако если не линковать, а джоинить то всё в порядке.

Исправлено, проверяйте [1.12.1.2](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.12.1.2)

> с файлами первого уровня всё впорядке но во вложеных папках в байты разделяются лишними знаками тире которые не нужны на самом деле.

Не смог воспроизвести

**Comment by kybyx** [comment]
> Исправлено, проверяйте [1.12.1.2]

Проверил, теперь Рлист по Прилинкованым файлам и папкам работает корректно.

>Не смог воспроизвести

Теперь это наблюдается только папке которую приджоинили
Попробуйте эти две команды :)
```
>>join https://cloud.mail.ru/public/BNYb/41fFCkRXX
>>rlist SamplesImages
```
Вот что у меня выдаёт
~~~~~~~~~~~~~~~~~~~~~
/test3/SamplesImages	10102511	2020.09.30 20:37:16	-	-
/test3/SamplesImages/kanzas	5960009	2020.09.30 20:37:17	-	-
/test3/SamplesImages/kanzas/fields	3133020	2020.09.30 20:37:17	-	-
/test3/SamplesImages/kanzas/fields/1395578-wheat.jpg	933723	2020.10.01 17:30:00	9B-8B-B5-0C-00-05-CD-E2-40-94-50-F0-23-84-06-40-60-A7-5F-29	-
/test3/SamplesImages/kanzas/fields/2c89d0e1629c4d0899fbdd419dfd03e9.max-2000x1000.jpg	464823	2020.10.01 17:29:52	C3-35-04-32-E5-C3-93-58-28-64-D2-09-CA-27-A6-8E-3A-0B-85-30	-
/test3/SamplesImages/kanzas/fields/kansas-wheat-panorama-panoramic-photo-wallpaper.jpg	1734474	2020.10.01 17:30:02	A6-FE-5A-B9-CE-E4-97-D1-C3-9D-D9-F3-43-B9-CE-22-12-30-31-5A	-
/test3/SamplesImages/kanzas/Kansas-740x431@2x.jpg	214886	2020.10.01 17:29:52	09-25-99-6C-FA-BE-84-35-52-12-97-7D-74-44-5F-54-A2-CD-09-12	-
/test3/SamplesImages/kanzas/Kanzas_Siti.jpg	411408	2020.10.01 17:29:52	30-BC-9A-44-ED-1F-E1-8C-E5-A6-71-9F-F2-EF-3E-39-00-F9-3B-86	-
/test3/SamplesImages/kanzas/kanzas-siti-ssha-missuri-doma.jpg	2200695	2020.10.01 17:29:56	5D-CB-3D-B8-C0-6E-CB-FE-12-3E-87-83-A9-DB-4D-B2-61-87-76-26	-
/test3/SamplesImages/nbrska	1323774	2020.09.30 20:37:17	-	-
/test3/SamplesImages/nbrska/1081-waco-1500px.jpg	220920	2020.10.01 17:29:59	1F-DC-1B-CD-75-E5-AD-6A-D1-28-10-9E-73-5F-55-A6-86-9A-48-22	-
/test3/SamplesImages/nbrska/20150619SC8A2902.jpg	350905	2020.10.01 17:30:02	35-22-9C-E4-FD-EF-3B-1A-64-A4-C6-21-70-31-CA-A3-A6-38-BC-10	-
/test3/SamplesImages/nbrska/Omaha(002)_1280x720.jpg	751949	2020.10.01 17:30:00	98-EC-5B-B2-8D-DA-BF-F7-96-A7-ED-51-0A-B3-F1-74-ED-91-FC-68	-
/test3/SamplesImages/starsky	1642862	2020.09.30 20:37:17	-	-
/test3/SamplesImages/starsky/1749846.jpg	312949	2020.10.01 17:30:01	24-F2-65-F4-82-28-D6-D2-1A-C4-AE-61-80-6D-C5-BE-13-AE-4D-85	-
/test3/SamplesImages/starsky/48235234.jpg	282023	2020.10.01 17:30:01	93-11-C2-0C-A5-A5-F5-2E-4A-69-AF-B3-55-99-E7-78-D8-C5-96-8F	-
/test3/SamplesImages/starsky/8124.jpg	1047890	2020.10.01 17:30:04	12-86-E7-35-3D-DA-AE-59-66-31-46-AB-B1-1E-61-71-04-DB-B9-B6	-
/test3/SamplesImages/yeld-harvestering.jpg	1175866	2020.10.01 17:29:52	23D43740AEAB609A71E5A55911F0BB1F415A589F	-
~~~~~~~~~~~~~~~~~~~~~
