### ISSUE TITLE
Зависание при работе с файлами 

### ISSUE THREAD

**Issue by Pavel-Vinogradov** [yar229/WebDavMailRuCloud#209]
Привет испльзую  v.1.12.1 
ОС Ubuntu 20.04.1 LTS 
При открытии видео всегда зависает, облоко использую в основном для хранения видео 
что может быть ? 
![Снимок экрана от 2020-10-21 20-55-41](https://user-images.githubusercontent.com/65782910/96758955-191f0f00-13e0-11eb-9f9a-9fb11900f905.png)

**Comment by yar229** [comment]
Плеер сначала скачивает видео полностью и только потом его проигрывает, выглядит как "зависает"

**Comment by yar229** [comment]
1. Обновите wdmrc до версии [1.12.2.0](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.12.2.0)
2. Установите SMPLayer - он поддерживает частичное скачивание, про другие не знаю.
3. В меню плеера Open -> Url -> `http://ip:port/path/video.avi`  или сразу с логином-паролем  `http://login%40mail.ru:password@ip:port/path/video.avi`

Если не трудно, напишите тут, всё ли получилось.

**Comment by Pavel-Vinogradov** [comment]
> 1. Обновите wdmrc до версии [1.12.2.2](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.12.2.2)
> 2. Установите SMPLayer - он поддерживает частичное скачивание, про другие не знаю.
> 3. В меню плеера Open -> Url -> `http://ip:port/path/video.avi`  или сразу с логином-паролем  `http://login%40mail.ru:password@ip:port/path/video.avi`
> 
> Если не трудно, напишите тут, всё ли получилось.

Привет 
поробовал программа работает корректно , а само облоко  работает не корректно или что то блокируею видео поток
, копирую ссылку на видео вставляю в проигрыватель , и эффект 0. возможно где то я не то что то сделал

https://cloud.mail.ru/public/4scX/zbmCzkEz2 вот ссылка на видео попробуй 
может получится

**Comment by yar229** [comment]
Смотри

Ubuntu 20.04.1 LTS 64bit

wmrc запущен на `127.0.0.1:3332`
файл в облаке лежит по пути `/10/Polet.mp4`
мой емейл  `login@mail.ru`
мой пароль `password`

SMPlayer ->  Open -> Url -> `http://login%40mail.ru:password@127.0.0.1:3332/10/Polet.mp4`

работает
