### ISSUE TITLE
Не удаётся подключиться через файловый менеджер Dolphin

### ISSUE THREAD

**Issue by 1690147** [yar229/WebDavMailRuCloud#219]
При попытке подключения появляется окно авторизации, после ввода логина и пароля появляется надпись: «Файл или папка webdav://127.0.0.1:8010/ не существует.»

Пробовал прописывать пути к директориям, но всё равно та же ошибка. Другие файловые менеджеры подключаются без проблем.

К webdavs://webdav.yandex.ru/ Dolphin подключается успешно.

Используется WebDAVCloudMailRu-1.11.0.31-dotNet48.

**Comment by yar229** [comment]
Обновитесь до версии https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.13.2.0

**Comment by yar229** [comment]
WebDAVCloudMailRu-1.13.2.0-dotNet5.zip
dotNet 5.0.100
Ubuntu 20.04.2 LTS
Dolphin 19.12.3

работает

**Comment by yar229** [comment]
На всякий случай - у вас в посте адрес указан webdav://127.0.0.1:8010, по умолчанию сервер запускается на webdav://127.0.0.1:801

**Comment by 1690147** [comment]
> Обновитесь до версии https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.13.2.0
> В идеале - переехать на dotnet5 (WebDAVCloudMailRu-1.13.2.0-dotNet5.zip)

Спасибо! Через WebDAVCloudMailRu-1.13.2.0-dotNet48 успешно подключился.

Проверил WebDAVCloudMailRu-1.13.2.0-dotNet5 — тоже полёт нормальный.
