### ISSUE TITLE
Linux и терминал

### ISSUE THREAD

**Issue by wzooroo** [yar229/WebDavMailRuCloud#222]
Никак не пойму как прописать логин и пароль на серверной версии линукс? "В файловом менеджере жмём ctrl+L и в строку вписываем dav://127.0.0.1:8888 " как это применить без десктопной версии линукс?

**Comment by yar229** [comment]
wdmrc - это "сервер", к нему обращаются "клиенты"
файловый менеджер - это клиент, он посылает команды (в том числе аутентификацию в виде логина-пароля) серверу и получает от него ответы.

В случае консоли в качестве клиента можно
* например, подключить в виде папки с помощью davfs2
* использовать консольный клиент, например, cadaver
