### ISSUE TITLE
dotNet - what they're for?

### ISSUE THREAD

**Issue by rediffusion** [yar229/WebDavMailRuCloud#224]
Interesting about these two:
```
WebDAVCloudMailRu-1.13.4.3-dotNet5.zip
WebDAVCloudMailRu-1.13.4.3-dotNetCore31.zip
```

Buy the way... I'm using "WebDAVCloudMailRu-1.13.4.3-dotNet48.zip" which works fine!

**Comment by yar229** [comment]
Builds for .NET, .Net core and the (last) .NET 5.0
https://github.com/yar229/WebDavMailRuCloud#requirements-
