### ISSUE TITLE
Please update to .NET 6.0

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#230]
Please update to .NET 6.0
https://www.reddit.com/r/Fedora/comments/unes3o/is_dotnetsdk50_no_longer_provided_on_fedora_36/
.NET 5.0 is End-of-Life'd on May 8, 2022

_Originally posted by @qtlin in https://github.com/yar229/WebDavMailRuCloud/issues/227#issuecomment-1126992947_

**Comment by yar229** [comment]
[1.13.6.0](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.13.6.0)

**Comment by qtlin** [comment]
I don't know anything changed on mail ru side, webdav login fails. is it because now requires application specific password or something else? How to enable verbose and/or debug output?

**Comment by yar229** [comment]
Nothing changed, take a look at the Logs folder

**Comment by qtlin** [comment]
Nothing on console other then connect/disconnect. How to enable verbose debugging? There is no Logs folder under extracted location.

**Comment by qtlin** [comment]
I ran dotnet under strace -f and see no attempts making any outgoing connection whatsoever.
