### ISSUE TITLE
.NET 6 as service

### ISSUE THREAD

**Issue by redscotina** [yar229/WebDavMailRuCloud#232]
Win10x64 | ver. 1.13.6.1
Version for .NET 6 from FAQ 

```
>WebDAVCloudMailRu>wdmrc.exe --install wdmrc -p 801 --maxthreads 15

>WebDAVCloudMailRu>net start wdmrc
System error 2 has occurred.

The system cannot find the file specified.
```

Что я делаю не так?
Более подробного описания подключения как сервис ненашел
(https://habr.com/ru/post/357822/comments/#comment_9873424) - походу стерт

Служба так и не появлялась в списке служб

**Comment by yar229** [comment]
Функционал установки виндоус сервиса есть только в версии Net48
Для остальных... возможно, однажды сделаю :)
Попробуйте https://nssm.cc/
