### ISSUE TITLE
Wrong rename

### ISSUE THREAD

**Issue by stiv-sigmal** [yar229/WebDavMailRuCloud#24]
Hello!

- Run WDMRC, map wdmrc-disk;
- Put `test.txt` there;
- Try to rename `test.txt` to test.diz (or `another-test.txt` for example);
- Got `test (1).txt` in any case of new name and extention.

_By the way, NetBox plugin (FTP, SFTP, WebDav) for FAR Manager also doesn't work with WDMRC. Instead folders there are files with 0 bytes sizes. But `CD FOLDER` command work. Files also have 0 bytes sizes. Don't want make new issue, because that's problem of NetBox, but inform you._

**Comment by yar229** [comment]
fixed in #25 
https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.0.129

Thanks for reporting NetBox problem, I'll try to do something )

**Comment by yar229** [comment]
P.S. 
NetBox fixed in  #27 
https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.0.133
