### ISSUE TITLE
Яндекс.Диск - перестали скачиваться файлы

### ISSUE THREAD

**Issue by ZZZConsulting** [yar229/WebDavMailRuCloud#241]
На днях при скачивании с Яндекс.Диска появилось зависание до таймаута.
Папки читают и создаются, файлы закачиваются, но скачать не получается.

Если нужно решение, можно попробовать fork
[https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.3](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.3)

**Upd: Последняя рекомендуемая версия
[https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.5](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.5)**

**Comment by KoSMM** [comment]
Добрый день!
Не заработал ваш форк. Версия WebDAVCloudMailRu-1.13.6.3-net48
403 Forbidden.

Оригинальная версия WebDAVCloudMailRu-1.13.6.1-dotNet48 работает, но не скачивает файлы с ЯД.

**Comment by ZZZConsulting** [comment]
Взял сейчас WebDAVCloudMailRu-1.13.6.3-net48 с GitHub'а из Release.
Поставил в отдельную папку, сверху записал свой конфиг и 2 батника - старт и стоп.
Запустил и проверил - все работает.
Что именно и на каком этапе дает 403 Forbidden?
Вариантов масса.
1) Все манипуляции по установке и настройке надо выполнять под администратором - "Run As Administrator".
2) Порт, на который вешается WebDav сервиса. На некоторые порты ниже 1024 система тупо не позволяет вешать.
3) Если WebDAVCloudMailRu ставится сервисом, то надо удалить предыдущую версию - остановить сервис и сделать Uninstall - установщики у базовой версии и у fork'а малость различаются, один другого может не сместить или что-то сделать не так. Поэтому лучше сначала удалить, а потом поставить.

Если применяется YandexAuthBrowser, то здесь дополнительно нужно проверять соблюдение условий:
1) Папка, где лежит и откуда запускается YandexAuthBrowser должна иметь полные права на чтение-запись-создание папок для учетной записи, под которой программа запускается - она создает папки и файлы. Нет прав - не работает.
2) Порт в YandexAuthBrowser должен быть свободен, не быть ниже 1024.
3) в wdmrc.config пароль (выглядит как Guid) для подключения к YandexAuthBrowser должен до символа совпадать с заданным в YandexAuthBrowser (пробелы и регистр важны).
4) Если в wdmrc.config задается CacheDir, то папка должна быть доступна на чтение и на запись для учетной записи, под которой работает WebDAVCloudMailRu, а для начала, для проверки можно просто удалить этот атрибут.

Попробуйте все настроить, но WebDAVCloudMailRu не ставить сервисом, а запустить в консоли чтобы видеть информацию, что он выдает в консоль.
На каком этапе и в каком виде выдается 403 Forbidden?
При запуске YandexAuthBrowser, при запуске WebDAVCloudMailRu, при подключении к WebDAVCloudMailRu?
Выдается ли окно браузера в программе YandexAuthBrowser?
Или как раз в ней не получается зайти в учетную запись?

YandexAuthBrowser требует .NET 7.0. Если он не установлен и программа не запускается, скачать и установить можно отсюда https://dotnet.microsoft.com/en-us/download?initial-os=windows
Так же можно попробовать версию [WebDAVCloudMailRu-1.13.6.3-net7.0-windows.zip](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/download/v1.13.6.3/WebDAVCloudMailRu-1.13.6.3-net7.0-windows.zip)
Именно эту, с "windows" на конце, т.к. просто net7.0 версия мультиплатформенная не содержит установку сервисом Windows.

И, пожалуй, самое важное, - запускать WebDAVCloudMailRu надо с --protocol YadWebV2
Только с ним работает YandexAuthBrowser и только этот протокол поддерживает fork, остальное присутствует, но даже не проверяется на работоспособность, т.к. у меня ни один, кроме YadWebV2, не работает вообще ни в какую, из-за чего, собственно, YadWebV2 и был сделан.

Если дадите немного больше деталей, возможно, получится понять в чем дело.

**Comment by ZZZConsulting** [comment]
И на случай, если кто-то сможет и захочет исправить оригинальный WebDAVCloudMailRu чтобы снова работало скачивание.
Файл
MailRuCloud/MailRuCloudApi/Base/Repos/YandexDisk/YadWeb/Models/GetResourceUrl.cs
Строку
            yield return new KeyValuePair<string, string>($"id.{index}", WebDavPath.Combine("/disk", Path));
надо заменить на
            yield return new KeyValuePair<string, string>($"idResource.{index}", WebDavPath.Combine("/disk", Path));

Все!

**Comment by KoSMM** [comment]
За длинный текст и попытку вникнуть в проблему спасибо. Ваша форк ушел несколько вперед, мне не нужны все его возможности, не запускаю его как сервис и не использую YandexAuthBrowser (не нужно запускать с правами админа), номер порта у меня один и тот же, что используется с оригинальной версией и все работает (поэтому с портом проблем быть не должно). Я использую утилиту исключительно в консольном режиме (вызывается скриптом из duplicati при создании резервной копии на яндекс, а потом закрывается). Т.е. все, что я делаю, когда обновляю версию - в папке с утилитой заменяю все файлы на файлы от новой версии.
Лог выкладываю ниже, возможно, придет мысль, в чем может быть проблема. Но особо вас не хочу напрягать, не стоит проблема одного человека, такого глубокого погружения :)
Скорее всего, причина в том, что "Только с ним работает YandexAuthBrowser и только этот протокол поддерживает fork, остальное присутствует, но даже не проверяется на работоспособность". А я, как раз, использую все по-старинке.

За исправление спасибо. Осталось только найти, как это скомпилировать :) Я последний раз программировал/компилировал 20 лет назад и для меня сейчас это целая проблема, чтобы поставить C#, разобраться, как там компилировать и т.д. Поэтому мне придется подождать, возможно, кто-то более продвинутый или автор, сделает рабочую версию.

`[8]: PROPFIND:http://127.0.0.1:3332/_PATH/:127.0.0.1:3332 - Start proce
ssing
[8]: Cloud instance created for _name_@yandex.ru
[9]: HTTP:GET:https://passport.yandex.ru/auth (128 ms)
[11]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_s
tep/start (151 ms)
[6]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_st
ep/commit_password (23 ms)
[8]: Unexpected exception while handling request (method=PROPFIND, url=http://12
7.0.0.1:3332/_PATH/, source=127.0.0.1:3332
System.AggregateException: One or more errors occurred. ---> System.AggregateExc
eption: One or more errors occurred. ---> System.Net.WebException: The remote se
rver returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron
ization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at YaR.Clouds.Base.Requests.BaseRequest`2.<MakeRequestAsync>d__8.MoveNext() i
n D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\MailRuCloud\MailRuCloudApi\Base\Req
uests\BaseRequest.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebAuth.<MakeLogin>d__3.MoveNex
t() in D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\MailRuCloud\MailRuCloudApi\Bas
e\Repos\YandexDisk\YadWeb\YadWebAuth.cs:line 41
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.<get_CachedAuth>
b__10_0(YadWebAuth _) in D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\MailRuCloud\
MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebRequestRepo.cs:line 62
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at YaR.Clouds.Common.Cached`1.RefreshValueIfNeeded() in D:\.TS-Git\ZZZConsult
ing\WebDavMailRuCloud\MailRuCloud\MailRuCloudApi\Common\Cached.cs:line 44
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.get_CachedAuth()
 in D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\MailRuCloud\MailRuCloudApi\Base\R
epos\YandexDisk\YadWeb\YadWebRequestRepo.cs:line 62
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.<AccountInfo>d__
32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at YaR.Clouds.Base.Account.<LoginAsync>d__14.MoveNext() in D:\.TS-Git\ZZZCons
ulting\WebDavMailRuCloud\MailRuCloud\MailRuCloudApi\Base\Account.cs:line 54
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at YaR.Clouds.Cloud..ctor(CloudSettings settings, Credentials credentials) in
 D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\MailRuCloud\MailRuCloudApi\Cloud.cs:
line 59
   at YaR.Clouds.WebDavStore.CloudManager.CreateCloud(HttpListenerBasicIdentity
identity) in D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\WebDavMailRuCloudStore\C
loudManager.cs:line 47
   at YaR.Clouds.WebDavStore.CloudManager.Instance(IIdentity identityi) in D:\.T
S-Git\ZZZConsulting\WebDavMailRuCloud\WebDavMailRuCloudStore\CloudManager.cs:lin
e 27
   at YaR.Clouds.WebDavStore.StoreBase.LocalStore.<GetItemAsync>d__9.MoveNext()
in D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\WebDavMailRuCloudStore\StoreBase\L
ocalStore.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NWebDav.Server.Handlers.PropFindHandler.<HandleRequestAsync>d__3.MoveNext(
) in D:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\NWebDav\NWebDav.Server\Handlers\
PropFindHandler.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext() in D
:\.TS-Git\ZZZConsulting\WebDavMailRuCloud\NWebDav\NWebDav.Server\WebDavDispatche
r.cs:line 137
---> (Inner Exception #0)`

**Comment by ZZZConsulting** [comment]
Если я правильно идентифицировал, ошибка классическая, - если вход только по логину и паролю, Яндекс блокирует учетку, принудительно переводит на подтверждение по СМС и отказывается дальше работать. Нужно снова менять в настройках на использование только логина и пароля, а затем делать множественные входы-выходы для тренировки их анализатора.
Иногда начинает работать, иногда нет.

Подготовлена новая версия. Скачивание исправлено для протокола YadWeb: [1.13.6.4](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.4)
(никаких иных изменений не делалось).

Если надоест тренировать анализатор, рекомендую все же обратить внимание на версию протокола YadWebV2. Она создавалась ровно по этой причине. При потребности на ПК открывается окно браузера, делается вход, куки, выданные сервером в ответ на аутентификацию, запоминаются, а потом используются пока не будет сделан выход из учетной записи или "выйти на всех устройствах". Одна проблема - куки должны держаться в сохранности, чтобы никто не стырил. Тут как с паролем от личного кабинета банка.

Ну и кстати, WebDavMailRuCloud и YandexAuthBrowser могут стоять на разных машинах. Если duplicati у Вас пылесосит на одной машине, а Вы сидите за совершенно другой, да хоть в другой половине континента - главное чтобы входящее подключение устанавливалось, чтобы Вы могли залогиниться в тот момент, когда это будет востребовано.

Пробуйте, проверяйте.
Надеюсь поможет.

**Comment by KoSMM** [comment]
Увы, не заработала. Но, вообще, странно то что вы пишите про блокировку. Я захожу с одного и того же IP, одним и тем же клиентом (или в вашей версии user-agent отличается от оригинальной версии WebDAVCloudMailRu-1.13.6.1-dotNet48.zip?), и он начинает меня б-403-лочить.
Я тут же запускаю все то же самое с оригинальной версией 1.13.6.1 и он меня прекрасно пускает. По идее, я для яндекса один и тот же клиент.
Далее ... :)
Захожу через браузер, тоже пускает. Захожу с другого IP через браузер, тоже пускает.
Смс не спрашивает (он вообще у меня смс почти никогда не спрашивает - видимо, по IP помнит, откуда и какими клиентами я обычно захожу).
При этом захожу в яндекс и пр. подобные сервисы всегда только через приватные окна, т.е. авторизационных куков в браузерах не сохранено.

**Comment by KoSMM** [comment]
Дополню.
По поводу "_В сообщениях в консоли это выглядит примерно так:
https://passport.yandex.ru/registration-validations/auth/multi_step/commit_password_"
сравнил логи рабочей авторизации оригинальной версии 1.13.6.1 и вашей версии 1.13.6.4.
И тат и там присутствует эта строка.
Удачная авторизация старой версией:

`[1]: WebDAV server running at http://127.0.0.1:3332/
[5]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Start processing
[5]: Cloud instance created for 
[3]: HTTP:GET:https://passport.yandex.ru/auth (166 ms)
[6]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_st
ep/start (269 ms)
[11]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_s
tep/commit_password (683 ms)
[11]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/account
s (154 ms)
[8]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/addition
al_data/ask_v2 (97 ms)
[9]: HTTP:GET:https://disk.yandex.ru/client/disk (14 ms)
[8]: HTTP:POST:https://disk.yandex.ru/models/?_m=space (186 ms)
[5]: Loading links from item.links.wdmrc
[11]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources,resourceSta
ts (133 ms)
[6]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources,resourceStat
s (193 ms)
[11]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Finished processing (3053
ms, HTTP result: 207)`

Неудачная авторизация в 1.13.6.4:
`[1]: WebDAV server running at http://127.0.0.1:3332/
[5]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Start processing
[5]: Cloud instance created for 
[3]: HTTP:GET:https://passport.yandex.ru/auth (295 ms)
[6]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_st
ep/start (380 ms)
[8]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_st
ep/commit_password (24 ms)
[5]: Unexpected exception while handling request (method=PROPFIND, url=http://12
7.0.0.1:3332/, source=127.0.0.1:3332
System.AggregateException: One or more errors occurred. ---> System.AggregateExc
eption: One or more errors occurred. ---> System.Net.WebException: The remote se
rver returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron
ization)
--- End of stack trace from previous location where exception was thrown ---`

**Comment by ZZZConsulting** [comment]
У меня три варианта на пробу, третий - крайний.

№1
В wdmrc.config задать
```
<DefaultUserAgent serializeAs="String">Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36</DefaultUserAgent>
<DefaultSecChUa serializeAs="String">" Not A; Brand;v="99", "Chromium";v="99", "Google Chrome";v="99"</DefaultSecChUa>
```

№2
В wdmrc.config задать
```
<DefaultUserAgent serializeAs="String">Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36</DefaultUserAgent>
<DefaultSecChUa serializeAs="String">" Not A; Brand;v="99", "Chromium";v="99", "Google Chrome";v="99"</DefaultSecChUa>
```

№3
[Исправленная оригинальная версия](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.1.Original%2B])
Этот вариант наименее предпочтительный, т.к. на поддержку этого варианта в дальней вряд ли можно рассчитывать.

Обязательно пишите, какой вариант заработает.

**Comment by KoSMM** [comment]
Хорошо, спасибо, потестю, отпишусь.

**Comment by KoSMM** [comment]
Добрый день! Прошу прощения, что пропал на 3 дня ... "то понос, то золотуха", руки не доходили :(
Первое, что выяснилось за эти три дня: оказалось, что с mail.ru у меня еще не работает оригинальная версия 1.13.6.1, не стал разбираться в причинах, просто откатился на более раннюю версию, которая стояла до недавнего времени (пока яндекс не стал дурить и я не обновился на последнюю версии, а потом на ваш форк).
1) Ваша версия 1.13.6.4 + User-Agent "... 105.0.0.0 ..."
403 Forbidden :(

2) Ваша версия 1.13.6.4 + User-Agent "... 78.0.3904.108 ..."
403 Forbidden :(

3) **Мод на оригинальную версию работает!**
_Как обычно, рефакторинг приводит к новым багам (ни в коем случае не хочу вас обидеть (вам большое спасибо за то, что развиваете проект, не даете ему умереть), просто констатирую очередное, уже неизвестно какое по счету, доказательство этого печального факта)_
_Только у вас в ссылке в конце лишний знак "[", поэтому ссылка битая._
_Вот правильная ссылка (для тех, кто будет скачивать):_
**https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.1.Original%2B**

**Еще раз Вам большое спасибо за помощь и за развитие проекта!**

**Comment by ZZZConsulting** [comment]
Весьма благодарю за помощь в разрешении ситуации!
Ссылку со скобкой подправил, спасибо!

У меня к Вам пара вопросов, если Вы не возражаете.

На Диск Яндекса, который все еще работает по логину и паролю, вход только через WebDavMailRuCloud? Через браузеры на этот Диск заходите или нет?
На свой я заходил часто, возможно анализатору Яндекса не понравилось, что User-Agent то новый, то древний.
Если на Ваш нет браузерных входов, только через WebDavMailRuCloud, можно предположить, что "счастливчиком" Вы являетесь как раз по этой причине.

И второй вопрос - можете попробовать еще одну подготовленную версию со старым протоколом YadWeb - будет или не будет работать с Вашим Диском?
Я обнаружил еще один момент, который возможно привел к 403 Forbidden. Хотелось бы проверить. И если заработает, чтобы не возвращаться к оригинальной версии - править и собирать несколько сборок параллельно несколько утомительно.

[Экспериментальная сборка](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.13.6.5)

Заранее благодарен!

**Comment by KoSMM** [comment]
Добрый день!
_>>На Диск Яндекса, который все еще работает по логину и паролю, вход только через WebDavMailRuCloud? Через браузеры на этот Диск заходите или нет?_
Нет, не только через WebDavMailRuCloud. В сам Я.Диск я захожу крайне редко (только когда что-то идет не так), но логинюсь в сервисы яндекса с этим логином/паролем регулярно. Логинюсь с этого же (серого) IP, что и WebDavMailRuCloud, но совершенно другим user-agent'ом (включая колонку Я.Алису), а также иногда логинюсь с других IP.

_>>И второй вопрос - можете попробовать еще одну подготовленную версию со старым протоколом YadWeb - будет или не будет работать с Вашим Диском?_
Проверил - **РАБОТАЕТ**! :) Буду вашей версией пользоваться. Еще раз спасибо!

**Comment by ZZZConsulting** [comment]
Отлично! Спасибо!

**Comment by yar229** [comment]
@ZZZConsulting  проект подзабросил, к сожалению, но огромное спасибо вам за новый протокол Яндекса и другие доработки! Включил в проект, [1.14.0.0](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.14.0.0)

**Comment by ZZZConsulting** [comment]
Приятно видеть Вас снова здесь в добром здравии!
И спасибо за возвращение!

К сожалению, не могу сказать, что последняя собранная мной версия беспроблемная, она по утрам после выхода ПК из сна на бэкапах выдает ошибки.
Уже который день сижу с дебагером, но поймать не могу.
Подозрений два.
На очистку кэша, которая случается не вовремя.
И на проблемы при параллельных обращениях к одним и тем же ресурсам.
Так что еще есть над чем работать ;-)

**Comment by ZZZConsulting** [comment]
Вышла следующая версия. Данный Issue закрыт.
