### ISSUE TITLE
Новая версия от ZZZConsulting, v1.24.10.31 - исправлена работа с Яндекс.Диском

### ISSUE THREAD

**Issue by ZZZConsulting** [yar229/WebDavMailRuCloud#249]
[Новая версия от ZZZConsulting, v1.24.10.31](https://github.com/ZZZConsulting/WebDavMailRuCloud/releases/tag/v1.24.10.31)
Эмулятор приведен в рабочее состояние.
Последняя протестированная версия API Яндекса - 383.0.0.

**Comment by ZZZConsulting** [comment]
@harmonyblend, обращаю внимание на обновление.

**Comment by harmonyblend** [comment]
Спасибо! Заработало всё!
