### ISSUE TITLE
Big file upload

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#36]
If I upload file bigger than permitted by mail.ru (via NetBox) - uploading speeds up after some seconds to very high speeds (500-600 Mbit/s on 100 Mbps internet) and no file in cloud after this.
Tests show us real max size of uploaded file:
"2147483456 bytes - file name in UTF-8 size in bytes"
Name only w/o folders names.

**Comment by C-A-T9LIFE** [comment]
If you have paid account - you can remove 2Gb filesize limitation using --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17/TCWFX(x64)"

**Comment by pasha-zzz** [comment]
I dont want remove limitation. I want get error if file isnt fits.

**Comment by yar229** [comment]
Thanks for reporting!
fixed #38

**Comment by yar229** [comment]
Some strange thing happen.
- NetBox trying to send big file.
- If file is larger than fits to cloud, I send "412 Precondition failed" webdav response.
- Then NetBox caches file in memory (at this time you see high speed numbers), and send it to webdav again!..
- Once more time "412 Precondition failed"
- And only after that NetBox shows error message.

Windows webdav client do the same things, 
Bitkinex works ok.
I really dunno what a hell and what to do with that...

**Comment by pasha-zzz** [comment]
Posted to NetBox plugin discussion thread - http://forum.farmanager.com/viewtopic.php?f=5&t=6317&p=141933#p141933

**Comment by yar229** [comment]
Fixed some errors, but -
It's windows webdav client normal behavior (for example, it happens so when you connect Yandex.Disk as drive)
Do not use cloud as windows drive :(
