### ISSUE TITLE
Bad Request (Invalid host) в ответе от сервера

### ISSUE THREAD

**Issue by zodo** [yar229/WebDavMailRuCloud#50]
Необходима возможность конфигурировать хост httplistener`а. Запускаю приложение в докере на vps, спрятав его за прокси с https. Хост, к которому подключаюсь, получается совсем не http://127.0.0.1 а что-то типа https://webdav.blbla.net, что и является причиной ошибки.

**Comment by zodo** [comment]
#51 собсно пул реквест

**Comment by yar229** [comment]
Залил пулреквест, спасибо
https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.5.4
