### ISSUE TITLE
No "Camera Uploads" folder

### ISSUE THREAD

**Issue by maxzaycev** [yar229/WebDavMailRuCloud#58]
Не вижу папку "Camera Uploads" в WebDav.

Mono, Mac OS Sierra.

**Comment by yar229** [comment]
Спасибо, не обращал внимания на это.
А у вас в этой папке есть какое-либо содержимое?

**Comment by maxzaycev** [comment]
Да

**Comment by yar229** [comment]
а через веб-интерфейс cloud.mail.ru видна?

**Comment by yar229** [comment]
Если ручками в Far'e написать
cd Camera Uploads
то заходит в нее
В CarotDAV тоже можно указать папку

(Это так, заметка на полях)

**Comment by yar229** [comment]
fixed ce0d932 [release v.1.5.25](https://github.com/yar229/WebDavMailRuCloud/tree/1.5.25)
