### ISSUE TITLE
wdmrc + davfs2: 400 Bad request

### ISSUE THREAD

**Issue by dm4g3** [yar229/WebDavMailRuCloud#61]
Пробую использовать wdmrc + davfs2, но при любой попытке маунта и в различных конфигурациях получаю:
/sbin/mount.davfs: Mounting failed.
400 Bad Request

При этом неясно, проблема в моих конфигах, в wdmrc или на стороне облака.
Нельзя ли поподробнее мануал о маунте таким способом?

**Comment by yar229** [comment]
К сожалению, то, что написано в readme - это практически максимум моих знаний про Linux /
А без монтирования работает из какого-нибудь файл менеджера?

**Comment by dm4g3** [comment]
С использованием dolphin'а вроде работает. Соответственно исключаются проблемы на стороне облака.
Но все таки ищу способ нормального маунта в davfs2.

**Comment by powerman** [comment]
@dm4g3 У меня через davfs2 работает, можем попробовать вместе сравнить конфигурации и отладить. Система у меня следующая:

- Hardened Gentoo Linux, 64-bit
- kernel 4.8.17-hardened
- mono 4.8.0.459
- wdmrc-mono 1.5.40
- davfs2 1.5.4

/etc/fstab
```
http://127.0.0.1:10801/	        /mnt/webdav.mailru	davfs rw,noauto 0 0
```

/etc/davfs2/davfs2.conf
```
[/mnt/webdav.mailru]
cache_size	0
delay_upload	0
use_locks       0
```

/etc/davfs2/secrets
```
http://127.0.0.1:10801/	        USERNAME@mail.ru	PASSWORD
```

wdmrc запущен как сервис под runit (извращения со script нужны из-за #57):
```
cd /opt/wdmrc-mono-1.5.40
exec chpst -u nobody script -qfec 'mono wdmrc.exe -p 10801' /dev/null
```
