### ISSUE TITLE
HTTP Range request

### ISSUE THREAD

**Issue by DesweR** [yar229/WebDavMailRuCloud#62]
Если выполнять GET запрос с указанием заголовка Range, то WebDavMailRuCloud:
1) Будет выкачивать целиком весь файл, а не диапазон байт, указанный в Range.
2) Пока файл целиком не скачает - не будет передавать получаемые данные клиенту, из за чего у последнего истечет время ожидания и он разорвет соединение.
3) Всё равно будет продолжать качать файл даже если клиент в этот момент разорвал соединение (закрыв сокет).

Если выставить запредельный таймаут у клиента и дождаться всё таки конца закачки, то WebDavMailRuCloud корректно вернёт клиенту указанный размер в Range.

**Comment by yar229** [comment]
Спасибо!
Вроде как изначально закладывался на это, но, видимо, испортил в процессе.
Быстрого исправления не обещаю, к сожалению

**Comment by yar229** [comment]
fixed https://github.com/yar229/WebDavMailRuCloud/commit/5c5eb3c5bd4ff5a3ea63c94e11cb24dab3ca271f

@DesweR, попробуйте [v.1.5.38](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.5.38)
