### ISSUE TITLE
Wrong used size

### ISSUE THREAD

**Issue by Nuke142** [yar229/WebDavMailRuCloud#63]
Only 12GB is used in cloud but Windows disk told me 205GB of 222GB is used.
PC system disk also have only 17GB free.... but this is absolutelly ridiculous :(
![scr](https://cloud.githubusercontent.com/assets/19406558/22826514/e212b2d2-efa3-11e6-89d2-d37bb6102a39.PNG)

**Comment by yar229** [comment]
[Microsoft says - it's not a bug, it's by design](https://support.microsoft.com/en-us/help/2386902/webdav-mapped-drive-reports-incorrect-drive-capacity)

**Comment by Nuke142** [comment]
I thouth it's only about full size not about free size too. So it's useless for windows :(

**Comment by yar229** [comment]
Are you sure you cannot write more than 222Gb?

(If so, you can use another client - Total Commander, Far, CarotDAV, BitKinex and others)
