### ISSUE TITLE
Released source is incomplete

### ISSUE THREAD

**Issue by powerman** [yar229/WebDavMailRuCloud#65]
It looks like released WebDavMailRuCloud-1.5.40.tar.gz is incomplete - it doesn't contains neither copy of Mail.Ru-.net-cloud-client subrepo nor required commit in that subrepo, so looks like it's impossible to build exactly same binary as released one using that source file.

**Comment by yar229** [comment]
Github makes this archive automatically
Use 
```
git checkout ...
git submodule update --recursive
```

**Comment by powerman** [comment]
I know I can just checkout the repo, my point is source archive is useless now and this probably should be mentioned somewhere in readme. Or you should record subrepo's commit somewhere outside .git/ to make it available within source archive, but if you won't be able to implement this as git hook then it might complicate build/release process. Also it may worth checking `submodule.<name>.branch` in `man gitmodules`, it doesn't say we can use commit instead of branch there, but it may works.
