### ISSUE TITLE
Package for Gentoo Linux

### ISSUE THREAD

**Issue by powerman** [yar229/WebDavMailRuCloud#66]
I've added package for Gentoo Linux into my overlay "powerman", you can check it here: https://github.com/powerman/powerman-overlay/blob/master/net-fs/wdmrc/wdmrc-1.5.40.ebuild

Only issue I've is wrong case of NWebDav.Server.dll file name (https://github.com/powerman/powerman-overlay/blob/master/net-fs/wdmrc/wdmrc-1.5.40.ebuild#L34), please let me know if you can fix this.

Now installing on Gentoo Linux is as simple as adding my overlay and installing the package (you can add this to README, if you like):
```
# layman -a powerman
# emerge wdmrc
```

I've opened this issue just to let you know, feel free to close it at any time.

**Comment by yar229** [comment]
Thanks for your work!

What about lib name - current status is waiting for https://github.com/ramondeklein/nwebdav/issues/13 and https://github.com/ramondeklein/nwebdav/pull/14

**Comment by vitaly-zdanevich** [comment]
https://github.com/powerman/powerman-overlay/blob/master/net-fs/wdmrc/wdmrc-1.5.40.ebuild 404

Please add to the main Gentoo tree.

**Comment by powerman** [comment]
I've removed ebuild because it's too outdated and because docker images works just fine last time I tried.

**Comment by vitaly-zdanevich** [comment]
It is easier to install from the main Portage tree, without Docker and overlays :(
