### ISSUE TITLE
Ошибка копирования файла размером более двух гигабайт

### ISSUE THREAD

**Issue by shustry** [yar229/WebDavMailRuCloud#68]
Файл (например видео) более двух гигабайт копируется в облако кусками по 2 гигабайта, но в нем не собирается обратно. Как быть?

**Comment by yar229** [comment]
Не понял вопрос.
Если вы про то, что через веб-интерфейс видите куски по 2Гб - это нормально, так и должно быть, ведь облако ограничивает размер файла.
Если смотреть через какой-нибудь вебдав-клиент - то увидите целый файл и так же целым файлом можно скачать.
