### ISSUE TITLE
100% загрузка процессора

### ISSUE THREAD

**Issue by kuimovvg** [yar229/WebDavMailRuCloud#71]
Если запустить как сервис
/usr/bin/mono-service /home/ubuntu/wdmrc-mono/wdmrc.exe --maxthreads 10 -h http://10.0.3.98 -p 32000
то грузится на 100% одно ядро процессора, если же
/usr/bin/mono /home/ubuntu/wdmrc-mono/wdmrc.exe --maxthreads 10 -h http://10.0.3.98 -p 32000
то загрузка обычно
Запускается на ubuntu 16.04, в lxc контейнере.

В приложении изменено только блок с логированием в файле wdmrc.exe.config
    <appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">

      <lockingModel type="log4net.Appender.FileAppender+MinimalLock"/>
      <file value="/var/log/wdmrc/" />
      <datePattern value="'wdmrclog-'yyyy-MM-dd'.log'" />
      <staticLogFileName value="false" />
      <appendToFile value="true" />
      <rollingStyle value="Composite" />
      <maxSizeRollBackups value="-1" />
      <maximumFileSize value="10MB" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
      </layout>      
    </appender>

    <root>
      <level value="ALL"/>
      
      <appender-ref ref="RollingLogFileAppender"/>
    </root>

**Comment by yar229** [comment]
У меня на lubuntu не воспроизвелось, но я подозреваю, что дело в ожидании ввода консолью.

Попробуйте 
```
nohup /usr/bin/mono-service /home/ubuntu/wdmrc-mono/wdmrc.exe --maxthreads 10 -h http://10.0.3.98 -p 32000
```

На днях выложу (предположительно) поправленную версию для теста

**Comment by kuimovvg** [comment]
Без изменений. Ощущение что проблема в том, что запущено в lxc контейнере/

**Comment by yar229** [comment]
Попробуйте вот этот вариант
[wdmrc_1.5.63_debug.zip](https://github.com/yar229/WebDavMailRuCloud/files/859486/wdmrc_1.5.63_debug.zip)

**Comment by kuimovvg** [comment]
В новом варианте загрузка нормальная

**Comment by yar229** [comment]
https://github.com/yar229/WebDavMailRuCloud/commit/48b313af3b40a0143a8fcb81c82453f205e4598a
Fixed in [1.5.63](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.5.63)
