### ISSUE TITLE
webdav getetag ошибки

### ISSUE THREAD

**Issue by g8tguy** [yar229/WebDavMailRuCloud#72]
При подключении через `davfs` все работает, но в логе на каждый файл идут две строки с ошибками!
Что это мжет значить? причем ошибками сыплет `mono wdmrc.exe -p 80`

```shell
[Threadpool worker]: Property {DAV:}getetag is not supported on item .
[Threadpool worker]: Property {http://apache.org/dav/props/}executable is not supported on item .
```

**Comment by yar229** [comment]
Не ошибки, предупреждения/уведомления.
На самом деле, там куча стандартных свойств и еще миллион сторонних, поддерживать все сложно, увеличится объем ответов и упадёт скорость.
Впрочем, DAV:getetag добавлю в ближайшем времени.
