### ISSUE TITLE
Неверный размер диска в Ubuntu

### ISSUE THREAD

**Issue by mwseven** [yar229/WebDavMailRuCloud#75]
Объём диска 1Тб, но система видит только занятое место.
# df -h /media/cloud.Mail/
Файл.система         Размер Использовано  Дост Использовано% Cмонтировано в
http://127.0.0.1:801    16G          16G 1008K          100% /media/cloud.Mail

**Comment by yar229** [comment]
Спасибо за репорт!

fixed https://github.com/yar229/WebDavMailRuCloud/commit/41e9ac6c17074fc37c12eadab320aae156e29ac9
release [1.5.64](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.5.64)

**Comment by yar229** [comment]
На всякий случай - облако mail.ru сообщает свободный/полный объём с точностью до мегабайта.
