### ISSUE TITLE
Cannot remove/rename files or folders.

### ISSUE THREAD

**Issue by firebbs** [yar229/WebDavMailRuCloud#78]
OS: Arch Linux 
4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux

Tried with kio and davfs2, same result.

davfs2:
\# sudo mono wdmrc.exe -p 804
\# sudo mount --rw -t davfs http://127.0.0.1:804 /mnt/mailru/ -o uid=1000
\# rm /mnt/mailru/backup/1 -R                                                                                                                                              
rm: cannot remove '/mnt/mailru/backup/1': Input/output error

output:
...
[Threadpool worker]: DELETE:http://127.0.0.1:804/backup/1/:127.0.0.1:804 - Start processing
[Threadpool worker]: Unable to delete '/backup/1' directory.
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
...

**Comment by zodo** [comment]
Maybe you are using login without _@mail.ru_ suffix. Try to add it to your login

**Comment by yar229** [comment]
> Maybe you are using login without @mail.ru suffix. Try to add it to your login

@firebbs -  yep, check it

**Comment by zodo** [comment]
@yar229 я бы добавил это в readme, либо выводил warning при запуске. Очень неочевидная проблема

**Comment by firebbs** [comment]
With @mail.ru suffix everything ok.
----
С суфиксом все работает Спасибо. 
Действительно стоит добавить в readme, т.к. без суфикса пускает, можно копировать создавать файлы, но с суфиксом только удалять и переименовывать не дает, что сбивает с толку.

**Comment by yar229** [comment]
added warning if domain does not contains domain part 
https://github.com/yar229/WebDavMailRuCloud/commit/71d8228f7909047b512d45b9dd5592d967d3adfc
