### ISSUE TITLE
При просмотре, вместо одной из папок (последней созданной?) подставляет текущую

### ISSUE THREAD

**Issue by Nicetas** [yar229/WebDavMailRuCloud#80]
Возможно, проблема из за того, что логин полностью цифровой (номер телефона). В листинге отсутствуют папки \@Soft и \@Soft\Games вместо них / и @Soft соответственно:

![img-2017-04-24-15-22-36](https://cloud.githubusercontent.com/assets/1893791/25337325/1b725f16-2904-11e7-8efb-a10810fc4bbb.png)
```M:\>dir
 Том в устройстве M не имеет метки.
 Серийный номер тома: 0000-0000

 Содержимое папки M:\

23.04.2017  18:28    <DIR>          .
23.04.2017  18:28    <DIR>          ..
24.04.2017  18:16     3 452 862 464 F3_GOTY.iso
23.04.2017  18:28    <DIR>          /
23.04.2017  18:28    <DIR>          @Android
23.04.2017  18:28    <DIR>          AYN-note
23.04.2017  18:28    <DIR>          Screenshots
               1 файлов 30 297 657 990 байт
               6 папок  28 173 103 104 байт свободно
```

![img-2017-04-24-15-29-34](https://cloud.githubusercontent.com/assets/1893791/25337391/60f2f212-2904-11e7-9f46-4fdc4caa134c.png)
```
M:\>dir @Soft
 Том в устройстве M не имеет метки.
 Серийный номер тома: 0000-0000

 Содержимое папки M:\@Soft

23.04.2017  18:28    <DIR>          .
23.04.2017  18:28    <DIR>          ..
23.04.2017  18:28    <DIR>          Hardware
23.04.2017  18:28    <DIR>          Office
23.04.2017  18:28    <DIR>          Service
23.04.2017  18:28    <DIR>          System
18.04.2017  14:56           951 416 rufus-2.13.exe
23.04.2017  18:28    <DIR>          @Soft
23.04.2017  18:28    <DIR>          Design
               1 файлов 27 399 701 568 байт
               8 папок  28 173 033 472 байт свободно
```

**Comment by yar229** [comment]
Что-то пока даже не знаю, что с этим делать.
Проявляется только при использовании средствами windows, все остальное испробованное ведет себя нормально (NetDrive, TotalCommander, CarotDAV, Far...)

**Comment by yar229** [comment]
Проблема в @ках

**Comment by Nicetas** [comment]
Извиняюсь, забыл отписаться. Настроил Netbox, всё заработало, спасибо.
Что касается @, так в названии второй папки его не было, или достаточно, что @ есть в пути?

**Comment by NewSky13** [comment]
Да, очень жаль, что в версии 1.5.65 всё так стало грустно. Проблема, описанная в этой теме и у меня. Я понимаю, что в Windows: "всё очень очень печально" (с), но ведь до версии 1.5.63 всё работает за-ме-ча-тель-но! А теперь, папки дублируются, те которые не пустые-пустые, в родительской, где еще масса папок вообще ничего нет. Точнее описать сложно, система непонятна, хотел записать видео (если нужно конечно запишу), а пока остаюсь на 1.5.63 она без проблем

**Comment by yar229** [comment]
Безумно странно, за две последних версии ничего такого, относящегося к путям, не трогал.
Если не трудно, набросайте еще инфы, что, как, когда

**Comment by NewSky13** [comment]
Отправил ссылку на видео с подробным описанием проблемы

**Comment by yar229** [comment]
fixed https://github.com/yar229/WebDavMailRuCloud/commit/903e34985866d8949d12feb9c4e33958369930a4

release [1.5.66](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.5.66)
