### ISSUE TITLE
Фичареквест: прокси

### ISSUE THREAD

**Issue by Dees7** [yar229/WebDavMailRuCloud#82]
Очень не хватает параметра "прокси" что бы сам wdmrc для доступа в инет использовал прокси (socks5)

**Comment by stiv-sigmal** [comment]
Учитывая, что в Украине с 19 мая блочат мэйл.ру, очень актуальная фича.

**Comment by C-A-T9LIFE** [comment]
ProxyCap

**Comment by dilbert2** [comment]
Можно покурить в сторону настроек в  application.config. Например, вот так можно его научить работать за корпоративным прокси с авторизацией;
```
<system.net>
        <defaultProxy enabled="true" useDefaultCredentials="true">
            <proxy bypassonlocal="True" usesystemdefault="True"/>
        </defaultProxy>
</system.net>
```

**Comment by yar229** [comment]
С Socks4-5 такое не пройдёт.
Проще всего, да - ProxyCap

**Comment by yar229** [comment]
Как бы совсем не по профилю проекта и реализуется сторонними средствами
(да и никогда руки не дойдут)
