### ISSUE TITLE
Синхронизация папок с общим доступом

### ISSUE THREAD

**Issue by eklstone** [yar229/WebDavMailRuCloud#84]
Уже существующие папки, созданные на другом аккаунте и расшаренные не синхронизируются.
Речь конкретно о Docker версии.

**Comment by yar229** [comment]
Не совсем понял вопрос.
Можно подробнее?

**Comment by eklstone** [comment]
Собственно вопрос, нормально ли что папки созданные кем-либо и расшаренные на мой аккаунт (им дан общий доступ по email-у), не закачиваются (их как-будто не существует), хотя если зайти через WEB, то папки есть. Папки созданные непосредственно с моего аккаунта (к примеру через сайт), прекрасно создаются и синхронизируются  (речь про docker версию на NAS от Synology).

Вот и не знаю в какую сторону "копать". Спасибо.

**Comment by yar229** [comment]
Все понятно, вскопал со своей стороны

fixed https://github.com/yar229/WebDavMailRuCloud/commit/c14e3a328fad79b91635fedd7397a4f9c906f728
release [1.5.67](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.5.67)
