### ISSUE TITLE
[REQ] Скачивание из паблик-папок

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#87]
В плаге для тотала сделано, что можно любую чужую паблик-папку добавить в рид-онли режиме.
Можно ли здесь сделать что-то подобное?
Например, в логине передаем адрес паблик-папки, пароль при этом пустой - тогда и сервер с этим объектом как с паблик-папкой работает.

**Comment by yar229** [comment]
Пока, к сожалению, нет близких планов что-то дописывать.

Как вариант, можно присоединить паблик-папку к своему аккаунту, например
`https://cloud.mail.ru/public/DLi7/8qJFH68dF` - создаем папку с именем `>>/DLi7/8qJFH68dF`

Не все клиенты позволят так сделать, но, как минимум, TotalCommander и Far позволяют.

**Comment by pasha-zzz** [comment]
Да, получилось. Только присоединять в корень нельзя, надо сначала зайти в другую папку. А можно сделать присоединение и по первоначальному урлу, чтобы ничего не править?

**Comment by yar229** [comment]
Да, сделаю на недельке

**Comment by yar229** [comment]
[v.1.6.1.3](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.6.1.3)

**Comment by pasha-zzz** [comment]
1.6.1.3 - вообще сломалось, и новым, и старым способом тоже выдает 500 Internal Server Error. Проверял в Far, Total, WinSCP

**Comment by yar229** [comment]
[v.1.6.1.4](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.6.1.4)

**Comment by pasha-zzz** [comment]
А нельзя просто по URL'у сделать создание, без >> в начале? ":", "/" все равно не могут быть в именах файлов облака.
Если регулякой - то что-то типа '^https:\/\/', или просто начинается с точной строки 'https://'. Или 'https://cloud.mail.ru/public/', если уж совсем точно.

**Comment by yar229** [comment]
Нет, планируется когда-нибудь однажды на это >> повесить еще несколько дополнительных функций, плюс там есть свои кривулины/хитрости
