### ISSUE TITLE
1.7.0.0 - перестало работать присоединение папок

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#89]
Сабжевая версия, при любых раскладах имеем ошибку 500, даже на тестовой папке из #87. До этого на 1.6.1.4 все работало (1.6.1.5 не ставил).

**Comment by yar229** [comment]
https://github.com/yar229/WebDavMailRuCloud/commit/36e88cfb991fa65c6047369e379de983b6632967 Спасибо, забыл проверить
[v.1.7.0.1](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.7.0.1)

**Comment by pasha-zzz** [comment]
Теперь работает, но в корень ни по >>, ни по >>link не мапится.
И при попытке создания в корне по >>link в файле item.links.wdmrc копятся записи об этой папке с "MapTo": ""

**Comment by yar229** [comment]
[1.7.0.2](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.7.0.2)
