### ISSUE TITLE
Не работает на Windows Server 2012 R2

### ISSUE THREAD

**Issue by kosenka** [yar229/WebDavMailRuCloud#90]
Не работает на Windows Server 2012 R2.
Как проверял:
start "WebDAV Cloud Mail.Ru" wdmrc.exe -p 3332 - запустился
далее
net use W: http://127.0.0.1:3332 [пароль] /USER:[имя_юзера@mail.ru]
Системная ошибка 67.
Не найдено сетевое имя.

И все :(

p.s. На windows 7 работает

**Comment by yar229** [comment]
а вот это делали?

[Windows] Разрешаем Basic Auth для встроенного в Windows WebDAV
→

Нажмите Win+R, Наберите regedit, нажмите OK
Идем по дереву в HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters
Щелкаем правой клавишей мыши на BasicAuthLevel, выбираем Modify
В поле Value пишем 2, щелкаем OK.
Перезагружаемся

**Comment by kosenka** [comment]
Сделал, но сервак, пока, не могу перезагрузить. Вечером перезагружу и проверю еще раз.

**Comment by yar229** [comment]
Можно не перегружать,

net stop webclient
net start webclient

**Comment by kosenka** [comment]
На этом серваке не установлена служба webclient
И так понимаю что без нее не будет работать?

**Comment by yar229** [comment]
Без нее не будет.
Можно заходить каким-либо сторонним клиентом - Total Commander, Far и т.д.
