### ISSUE TITLE
Не грузит более 500 файлов

### ISSUE THREAD

**Issue by Xim-QX** [yar229/WebDavMailRuCloud#91]
Родное ограничение веб-интерфейса мейл облака, за раз грузится 500 файлов, если файлов больше -
 они не подтягиваются.

**Comment by yar229** [comment]
А в у вас какая версия? Проверил на [1.7.0.3](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.7.0.3), как минимум, каталог с 601 файлом виден нормально

**Comment by Xim-QX** [comment]
Проблема решена, использовалась древняя версия
