### ISSUE TITLE
Не подгружает расшаренные папки

### ISSUE THREAD

**Issue by Xim-QX** [yar229/WebDavMailRuCloud#92]
Если в облаке есть своя папка, расшаренная для кого-либо, при листинге эту папку не видно.

**Comment by yar229** [comment]
Проверьте установленную версию, у меня на [1.7.0.3](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.7.0.3) не подтверждается.

**Comment by Xim-QX** [comment]
Благодарю за подсказку, проблема решена, использовалась древняя версия
