### ISSUE TITLE
Удаление линков на несуществующие файлы/папки

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#93]
На момент 1.7.1.27 не получается удалить.

**Comment by pasha-zzz** [comment]
Может команду, типа >>check - проверка всех ссылок в item.links.wdmrc. Возможно в лог записать битые имена, ссылки и к каким папкам были присоединены. Лог можно и на самом диске хранить.

**Comment by yar229** [comment]
fixed [1.8.0.7](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.8.0.7)
