### ISSUE TITLE
Нет доступа к облаку без файла item.links.wdmrc

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#98]
Если файла item.links.wdmrc в корне облака нет - выдает ошибку 404 при подключении. 1.8.0.1, на 1.7.1.27 было все ОК. Даже если загрузить через веб файл 0 размера - начинает работать.

**Comment by yar229** [comment]
Спасибо, починил в [1.8.0.3](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.8.0.3)
